import type{RuntimeManager}from'./runtime.js';
import type{ServiceId}from'./types.js';

interface HeadlessActions{toggleService(id:ServiceId):Promise<unknown>;toggleAll(start:boolean):Promise<unknown>}
interface RpcRequest{jsonrpc?:string;id?:string|number;method?:string;params?:{name?:string;arguments?:Record<string,unknown>}}

const tools=[
 {name:'localdeck_status',description:'Lees de lokale LocalDeck-status, services en resourcebelasting.',inputSchema:{type:'object',properties:{}}},
 {name:'localdeck_projects',description:'Toon projecten, lokale domeinen, PHP-versies en branches.',inputSchema:{type:'object',properties:{}}},
 {name:'localdeck_services',description:'Start of stop alle LocalDeck-services.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['start','stop']}},required:['action']}},
 {name:'localdeck_service',description:'Start of stop één LocalDeck-service.',inputSchema:{type:'object',properties:{service:{type:'string',enum:['apache','php','mysql','phpmyadmin','mail','redis']},action:{type:'string',enum:['toggle']}},required:['service','action']}},
 {name:'localdeck_inspector',description:'Lees de meest recente lokale inspectorgebeurtenissen en fouten.',inputSchema:{type:'object',properties:{limit:{type:'number',minimum:1,maximum:100}}}},
 {name:'localdeck_doctor',description:'Voer veilige projectgezondheidscontroles uit.',inputSchema:{type:'object',properties:{projectId:{type:'string'}}}},
 {name:'localdeck_production_parity',description:'Vergelijk een lokaal project met zijn productieprofiel in de Project Capsule.',inputSchema:{type:'object',properties:{projectId:{type:'string'}},required:['projectId']}},
 {name:'localdeck_preflight',description:'Voer de lokale CI-preflight voor een project uit.',inputSchema:{type:'object',properties:{projectId:{type:'string'}},required:['projectId']}},
 {name:'localdeck_safe_task',description:'Voer een vooraf gedefinieerde veilige taak uit voor een project.',inputSchema:{type:'object',properties:{projectId:{type:'string'},taskId:{type:'string'}},required:['projectId','taskId']}}
];

function result(value:unknown){return{content:[{type:'text',text:typeof value==='string'?value:JSON.stringify(value,null,2)}]}}

export function runMcpServer(runtime:RuntimeManager,actions:HeadlessActions){
 let buffer='';
 const send=(value:unknown)=>process.stdout.write(`${JSON.stringify(value)}\n`);
 const handle=async(message:RpcRequest)=>{if(message.method==='initialize'){send({jsonrpc:'2.0',id:message.id,result:{protocolVersion:'2025-03-26',capabilities:{tools:{}},serverInfo:{name:'localdeck',version:runtime.snapshot().update.currentVersion}}});return}if(message.method==='notifications/initialized')return;if(message.method==='ping'){send({jsonrpc:'2.0',id:message.id,result:{}});return}if(message.method==='tools/list'){send({jsonrpc:'2.0',id:message.id,result:{tools}});return}if(message.method==='tools/call'){try{const name=message.params?.name,args=message.params?.arguments??{};let value:unknown;if(name==='localdeck_status'){runtime.refreshResources();const state=runtime.snapshot();value={version:state.update.currentVersion,mode:state.settings.runtimeMode,installation:state.installation,services:state.services,resources:state.resourceUsage}}else if(name==='localdeck_projects'){value=runtime.snapshot().projects.map(project=>({id:project.id,name:project.name,domain:project.domain,php:project.phpVersion,branch:project.branch,blueprint:runtime.snapshot().blueprints.find(item=>item.projectId===project.id)}))}else if(name==='localdeck_services'){await actions.toggleAll(args.action==='start');value={ok:true,services:runtime.snapshot().services}}else if(name==='localdeck_service'){await actions.toggleService(String(args.service)as ServiceId);value={ok:true,service:runtime.snapshot().services.find(item=>item.id===args.service)}}else if(name==='localdeck_inspector'){runtime.collectInspector();value=runtime.snapshot().inspectorEvents.slice(0,Math.min(100,Math.max(1,Number(args.limit)||30)))}else if(name==='localdeck_doctor'){runtime.runProjectDoctor(args.projectId?String(args.projectId):undefined);value=runtime.snapshot().projectHealth}else if(name==='localdeck_production_parity'){runtime.runProductionParity(String(args.projectId));value=runtime.snapshot().productionParity.find(item=>item.projectId===args.projectId)}else if(name==='localdeck_preflight'){await runtime.runPreflight(String(args.projectId));value=runtime.snapshot().preflightReports.find(item=>item.projectId===args.projectId)}else if(name==='localdeck_safe_task'){const task=runtime.snapshot().tasks.find(item=>item.id===args.taskId);if(!task?.safe)throw new Error('Alleen vooraf gemarkeerde veilige taken zijn toegestaan via MCP.');value=await runtime.runTask(String(args.projectId),String(args.taskId))}else throw new Error('Onbekende LocalDeck-tool.');send({jsonrpc:'2.0',id:message.id,result:result(value)})}catch(error){send({jsonrpc:'2.0',id:message.id,error:{code:-32000,message:error instanceof Error?error.message:String(error)}})}return}if(message.id!==undefined)send({jsonrpc:'2.0',id:message.id,error:{code:-32601,message:'Methode niet gevonden'}})};
 process.stdin.setEncoding('utf8');process.stdin.on('data',chunk=>{buffer+=chunk;let newline=buffer.indexOf('\n');while(newline>=0){const line=buffer.slice(0,newline).trim();buffer=buffer.slice(newline+1);if(line)try{void handle(JSON.parse(line))}catch{send({jsonrpc:'2.0',error:{code:-32700,message:'Ongeldige JSON'}})}newline=buffer.indexOf('\n')}});process.stdin.resume();
}

export async function runCli(runtime:RuntimeManager,actions:HeadlessActions,command:string,argument?:string){let value:unknown;if(command==='status'){runtime.refreshResources();value=runtime.snapshot()}else if(command==='projects')value=runtime.snapshot().projects;else if(command==='start'){await actions.toggleAll(true);value=runtime.snapshot().services}else if(command==='stop'){await actions.toggleAll(false);value=runtime.snapshot().services}else if(command==='toggle'&&argument){await actions.toggleService(argument as ServiceId);value=runtime.snapshot().services.find(item=>item.id===argument)}else if(command==='doctor'){runtime.runProjectDoctor(argument);value=runtime.snapshot().projectHealth}else if(command==='parity'&&argument){runtime.runProductionParity(argument);value=runtime.snapshot().productionParity.find(item=>item.projectId===argument)}else if(command==='preflight'&&argument){await runtime.runPreflight(argument);value=runtime.snapshot().preflightReports.find(item=>item.projectId===argument)}else if(command==='logs'){runtime.collectServiceLogs();value=runtime.snapshot().logs.slice(0,100)}else if(command==='devdrive'){runtime.detectDevDrive();value=runtime.snapshot().devDrive}else throw new Error('Gebruik --localdeck-cli=status|projects|start|stop|toggle|doctor|parity|preflight|logs|devdrive en eventueel --service=apache of --project=<id>.');process.stdout.write(`${JSON.stringify(value,null,2)}\n`)}
