import{contextBridge,ipcRenderer}from'electron';

contextBridge.exposeInMainWorld('localdeck',{
 getState:()=>ipcRenderer.invoke('state:get'),toggleService:(id:string)=>ipcRenderer.invoke('service:toggle',id),toggleAll:(start:boolean)=>ipcRenderer.invoke('service:all',start),updateServicePort:(id:string,port:number)=>ipcRenderer.invoke('service:port',id,port),autoPort:(id:string)=>ipcRenderer.invoke('service:auto-port',id),inspectPort:(id:string)=>ipcRenderer.invoke('service:port:inspect',id),portAutopilot:(id:string)=>ipcRenderer.invoke('service:port-autopilot',id),inspectAllPorts:()=>ipcRenderer.invoke('ports:inspect-all'),saveStartProfile:(profile:unknown)=>ipcRenderer.invoke('start-profile:save',profile),deleteStartProfile:(id:string)=>ipcRenderer.invoke('start-profile:delete',id),applyStartProfile:(id:string)=>ipcRenderer.invoke('start-profile:apply',id),cancelOperation:(id:string)=>ipcRenderer.invoke('action:cancel',id),retryOperation:(id:string)=>ipcRenderer.invoke('action:retry',id),dismissOperation:(id:string)=>ipcRenderer.invoke('action:dismiss',id),clearCompletedOperations:()=>ipcRenderer.invoke('action:clear'),rollbackSafeChange:(id:string)=>ipcRenderer.invoke('safe-change:rollback',id),
 runDiagnostics:()=>ipcRenderer.invoke('diagnostics:run'),exportDiagnostics:()=>ipcRenderer.invoke('diagnostics:export'),exportSupportBundle:()=>ipcRenderer.invoke('diagnostics:bundle'),repairRuntime:()=>ipcRenderer.invoke('runtime:repair'),installRuntime:()=>ipcRenderer.invoke('runtime:install'),setRuntimeMode:(mode:string)=>ipcRenderer.invoke('runtime:mode',mode),syncDomains:()=>ipcRenderer.invoke('network:sync'),
 addProject:(project:unknown)=>ipcRenderer.invoke('project:add',project),scaffoldProject:(project:unknown)=>ipcRenderer.invoke('project:scaffold',project),importXampp:()=>ipcRenderer.invoke('project:xampp'),importLegacy:(kind:string)=>ipcRenderer.invoke('project:legacy',kind),importProjectManifest:()=>ipcRenderer.invoke('project:manifest:import'),writeProjectManifest:(id:string)=>ipcRenderer.invoke('project:manifest:write',id),updateProjectProfile:(id:string,patch:unknown)=>ipcRenderer.invoke('project:profile',id,patch),setProjectPhpVersion:(id:string,version:string)=>ipcRenderer.invoke('project:php-version',id,version),exportProject:(id:string)=>ipcRenderer.invoke('project:export',id),removeProject:(id:string,confirmation:string)=>ipcRenderer.invoke('project:remove',id,confirmation),openProject:(id:string,kind:string)=>ipcRenderer.invoke('project:open',id,kind),runComposer:(id:string,command:string)=>ipcRenderer.invoke('project:composer',id,command),
 cloneProject:(repositoryUrl:string,parentDirectory:string,name?:string)=>ipcRenderer.invoke('project:clone',repositoryUrl,parentDirectory,name),bootstrapProject:(id:string)=>ipcRenderer.invoke('project:bootstrap',id),createBranchEnvironment:(id:string,branch:string)=>ipcRenderer.invoke('project:branch:create',id,branch),removeBranchEnvironment:(id:string)=>ipcRenderer.invoke('project:branch:remove',id),refreshBlueprints:()=>ipcRenderer.invoke('project:blueprints'),runProjectDoctor:(id?:string)=>ipcRenderer.invoke('project:doctor',id),repairProject:(id:string)=>ipcRenderer.invoke('project:repair',id),runProductionParity:(id:string)=>ipcRenderer.invoke('project:parity',id),runPreflight:(id:string)=>ipcRenderer.invoke('project:preflight',id),runTestLab:(id:string)=>ipcRenderer.invoke('testlab:run',id),writeIdeIntegration:(id:string)=>ipcRenderer.invoke('project:ide',id),setProjectXdebug:(id:string,mode:string)=>ipcRenderer.invoke('project:xdebug',id,mode),runDependencyGuard:(id:string)=>ipcRenderer.invoke('engineering:dependency',id),generateSbom:(id:string)=>ipcRenderer.invoke('engineering:sbom',id),runDriftDetector:(id:string)=>ipcRenderer.invoke('engineering:drift',id),runMigrationLab:(id:string)=>ipcRenderer.invoke('engineering:migration',id),runRehearsal:(id:string)=>ipcRenderer.invoke('engineering:rehearsal',id),runReleaseGate:(id:string)=>ipcRenderer.invoke('engineering:release-gate',id),runPerformanceBaseline:(id:string)=>ipcRenderer.invoke('engineering:performance',id),runBrowserMatrix:(id:string)=>ipcRenderer.invoke('engineering:browser-matrix',id),runMailQuality:()=>ipcRenderer.invoke('engineering:mail-quality'),
 createSnapshot:(projectId:string,description?:string)=>ipcRenderer.invoke('snapshot:create',projectId,description),restoreSnapshot:(id:string)=>ipcRenderer.invoke('snapshot:restore',id),deleteSnapshot:(id:string)=>ipcRenderer.invoke('snapshot:delete',id),refreshSnapshots:()=>ipcRenderer.invoke('snapshot:refresh'),
 addTask:(task:unknown)=>ipcRenderer.invoke('task:add',task),deleteTask:(id:string)=>ipcRenderer.invoke('task:delete',id),runTask:(projectId:string,taskId:string)=>ipcRenderer.invoke('task:run',projectId,taskId),saveWorker:(worker:unknown)=>ipcRenderer.invoke('worker:save',worker),startWorker:(id:string)=>ipcRenderer.invoke('worker:start',id),stopWorker:(id:string)=>ipcRenderer.invoke('worker:stop',id),deleteWorker:(id:string)=>ipcRenderer.invoke('worker:delete',id),
 updateSettings:(patch:unknown)=>ipcRenderer.invoke('settings:update',patch),clearLogs:()=>ipcRenderer.invoke('logs:clear'),chooseDirectory:()=>ipcRenderer.invoke('dialog:directory'),openWorkspace:()=>ipcRenderer.invoke('workspace:open'),openWebsite:()=>ipcRenderer.invoke('website:open'),exportWorkspace:()=>ipcRenderer.invoke('workspace:export'),importWorkspace:()=>ipcRenderer.invoke('workspace:import'),
 createDatabase:(name:string,charset:string,collation:string)=>ipcRenderer.invoke('database:create',name,charset,collation),copyDatabasePassword:()=>ipcRenderer.invoke('database:credentials'),deleteDatabase:(id:string)=>ipcRenderer.invoke('database:delete',id),refreshDatabases:()=>ipcRenderer.invoke('database:refresh'),getDatabaseTables:(id:string)=>ipcRenderer.invoke('database:tables',id),queryDatabase:(id:string,query:string)=>ipcRenderer.invoke('database:query',id,query),importDatabase:(id:string)=>ipcRenderer.invoke('database:import',id),exportDatabase:(id:string)=>ipcRenderer.invoke('database:export',id),backupDatabase:(id:string)=>ipcRenderer.invoke('database:backup',id),restoreBackup:(id:string)=>ipcRenderer.invoke('database:restore',id),refreshBackups:()=>ipcRenderer.invoke('database:backups'),
 compareDatabaseSchemas:(leftId:string,rightId:string)=>ipcRenderer.invoke('database:schema:compare',leftId,rightId),getDatabaseUsers:()=>ipcRenderer.invoke('database:users'),createDatabaseUser:(databaseId:string,username:string,password:string)=>ipcRenderer.invoke('database:user:create',databaseId,username,password),deleteDatabaseUser:(username:string,host:string)=>ipcRenderer.invoke('database:user:delete',username,host),generateTestData:(id:string,table:string,count:number)=>ipcRenderer.invoke('database:testdata',id,table,count),anonymizeDatabase:(id:string)=>ipcRenderer.invoke('database:anonymize',id),importDatabaseSanitized:(id:string)=>ipcRenderer.invoke('database:import:safe',id),
 addMailAddress:(address:string,description:string,projectId?:string)=>ipcRenderer.invoke('mail:add',address,description,projectId),deleteMailAddress:(id:string)=>ipcRenderer.invoke('mail:delete',id),testMail:()=>ipcRenderer.invoke('mail:test'),togglePhpExtension:(id:string)=>ipcRenderer.invoke('php:extension',id),installDeveloperTool:(id:string)=>ipcRenderer.invoke('devtool:install',id),openTool:(id:string)=>ipcRenderer.invoke('tool:open',id),
 scanSecurity:()=>ipcRenderer.invoke('security:scan'),fixSecurity:(id:string)=>ipcRenderer.invoke('security:fix',id),repairAll:()=>ipcRenderer.invoke('repair:all'),togglePlugin:(id:string)=>ipcRenderer.invoke('plugin:toggle',id),collectLogs:()=>ipcRenderer.invoke('logs:collect'),
 refreshComponents:()=>ipcRenderer.invoke('components:refresh'),importComponentPack:()=>ipcRenderer.invoke('component:import'),inspectComponentPack:()=>ipcRenderer.invoke('component:inspect'),refreshInspector:()=>ipcRenderer.invoke('inspector:refresh'),refreshResources:()=>ipcRenderer.invoke('resources:refresh'),getFrameworkActions:(projectId:string)=>ipcRenderer.invoke('framework:actions',projectId),runFrameworkAction:(projectId:string,actionId:string)=>ipcRenderer.invoke('framework:run',projectId,actionId),
 importApiWorkspace:()=>ipcRenderer.invoke('api:import'),saveApiWorkspace:(workspace:unknown)=>ipcRenderer.invoke('api:save',workspace),deleteApiWorkspace:(id:string)=>ipcRenderer.invoke('api:delete',id),runApiRequest:(workspaceId:string,endpointId:string,body:string)=>ipcRenderer.invoke('api:run',workspaceId,endpointId,body),generateApiFixture:(workspaceId:string,endpointId:string)=>ipcRenderer.invoke('api:fixture',workspaceId,endpointId),createWebhookEndpoint:(name:string)=>ipcRenderer.invoke('webhook:create',name),deleteWebhookEndpoint:(id:string)=>ipcRenderer.invoke('webhook:delete',id),replayWebhook:(eventId:string,targetUrl:string)=>ipcRenderer.invoke('webhook:replay',eventId,targetUrl),saveReplayCapture:(capture:unknown)=>ipcRenderer.invoke('replay:save',capture),runReplayCapture:(id:string)=>ipcRenderer.invoke('replay:run',id),deleteReplayCapture:(id:string)=>ipcRenderer.invoke('replay:delete',id),
 startShare:(projectId:string,durationMinutes:number)=>ipcRenderer.invoke('share:start',projectId,durationMinutes),stopShare:(id:string)=>ipcRenderer.invoke('share:stop',id),copyShare:(id:string)=>ipcRenderer.invoke('share:copy',id),copyMcpConfig:()=>ipcRenderer.invoke('integration:copy-mcp'),copyCliCommand:()=>ipcRenderer.invoke('integration:copy-cli'),
 saveSecret:(key:string,value:string,projectId?:string)=>ipcRenderer.invoke('secret:save',key,value,projectId),deleteSecret:(id:string)=>ipcRenderer.invoke('secret:delete',id),detectDevDrive:()=>ipcRenderer.invoke('devdrive:detect'),
 refreshOfflineRuntime:()=>ipcRenderer.invoke('runtime:offline:refresh'),verifyRuntimePackages:()=>ipcRenderer.invoke('runtime:packages:verify'),assessReleaseReadiness:()=>ipcRenderer.invoke('release:readiness'),importOfflineRuntime:()=>ipcRenderer.invoke('runtime:offline:import'),exportOfflineRuntime:()=>ipcRenderer.invoke('runtime:offline:export'),prepareOfflineRuntime:()=>ipcRenderer.invoke('runtime:offline:prepare'),
 checkUpdates:(manual=false)=>ipcRenderer.invoke('update:check',manual),downloadUpdate:()=>ipcRenderer.invoke('update:download'),rollbackUpdate:()=>ipcRenderer.invoke('update:rollback'),dismissUpdate:()=>ipcRenderer.invoke('update:dismiss'),
 onStateChanged:(callback:(state:unknown)=>void)=>{const listener=(_:unknown,state:unknown)=>callback(state);ipcRenderer.on('state:changed',listener);return()=>ipcRenderer.removeListener('state:changed',listener)}
});
