export type ServiceId='apache'|'php'|'mysql'|'phpmyadmin'|'mail'|'redis';
export type ServiceStatus='running'|'stopped'|'starting'|'error';
export type RuntimeMode='application'|'windows-service';
export type AppLanguage='nl'|'en';
export type BackupSchedule='off'|'daily'|'weekly';
export type UpdateStatus='idle'|'checking'|'available'|'current'|'error';
export type WebServerKind='apache'|'nginx'|'caddy';
export type DnsMode='hosts'|'local-dns';
export type MailMode='capture'|'smtp-relay'|'local-server';
export type DatabaseEngine='mysql'|'mariadb'|'postgresql';
export type LocalDomainSuffix='localhost'|'test';
export type HealthStatus='ok'|'warning'|'error';

export interface ServiceState{id:ServiceId;name:string;description:string;status:ServiceStatus;port:number;version:string;installed:boolean;health:'healthy'|'unreachable'|'unknown';pid?:number;error?:string;restartCount?:number}
export interface ProjectProfile{webServer:WebServerKind;phpExtensions:string[];environment:'development'|'testing';databaseName?:string;databaseEngine:DatabaseEngine;databaseVersion:string;nodeVersion?:string;mailMode:MailMode;debugToolbar:boolean;isolated:boolean;runtimeLocked:boolean;xdebugMode:'off'|'debug'|'profile'|'trace'|'coverage';schedulerEnabled:boolean;httpPort?:number;httpsPort?:number;env:Record<string,string>}
export interface ProjectCertificate{status:'active'|'missing'|'disabled';certificateFile?:string;keyFile?:string}
export interface Project{id:string;name:string;path:string;domain:string;phpVersion:string;documentRoot?:string;secure:boolean;certificate?:ProjectCertificate;createdAt:string;template?:'custom'|'wordpress'|'laravel'|'symfony'|'drupal';profile?:ProjectProfile;production?:{php:string;database:string;webServer:WebServerKind;requiredEnv:string[]};repositoryUrl?:string;branch?:string;parentProjectId?:string;lastOpenedAt?:string}
export interface ProjectBlueprint{projectId:string;schemaVersion:number;file:string;lockFile:string;locked:boolean;hash:string;updatedAt:string;summary:string;warnings:string[]}
export interface BranchEnvironment{id:string;projectId:string;childProjectId:string;branch:string;path:string;domain:string;databaseName:string;databaseCloned?:boolean;httpPort:number;httpsPort:number;status:'ready'|'creating'|'error';createdAt:string;error?:string}
export interface RuntimeComponent{id:string;name:string;category:'webserver'|'language'|'database'|'service'|'tool';version:string;installed:boolean;active:boolean;verified:boolean;required:boolean;description:string;path?:string}
export interface InspectorEvent{id:string;at:string;projectId?:string;kind:'request'|'php'|'sql'|'queue'|'security'|'task';severity:'info'|'warning'|'error';title:string;detail:string;durationMs?:number;traceId?:string;spanId?:string;parentSpanId?:string;service?:string}
export interface ResourceUsage{capturedAt:string;appMemoryMb:number;serviceMemoryMb:number;totalMemoryMb:number;processes:{id:string;name:string;pid?:number;memoryMb:number}[]}
export interface ShareSession{id:string;projectId:string;url:string;token:string;expiresAt:string;status:'active'|'expired'|'stopped';createdAt:string;qrDataUrl?:string}
export interface FrameworkAction{id:string;projectId:string;name:string;description:string;command:string;args:string[];destructive:boolean;available:boolean}
export interface DatabaseSchemaDiff{left:string;right:string;onlyLeft:string[];onlyRight:string[];changed:{table:string;left:string;right:string}[]}
export interface DatabaseInfo{id:string;name:string;charset:string;collation:string;tables:number;size:string;createdAt:string}
export interface DatabaseTable{name:string;rows:number;engine:string;size:string;collation:string}
export interface DatabaseQueryResult{columns:string[];rows:Record<string,string|null>[];affectedRows?:number;durationMs:number;limited:boolean}
export interface DatabaseUser{user:string;host:string;plugin:string;locked:boolean}
export interface MailAddress{id:string;address:string;projectId?:string;description:string;createdAt:string}
export interface BackupInfo{id:string;database:string;file:string;size:string;createdAt:string}
export interface SnapshotInfo{id:string;projectId:string;projectName:string;file:string;size:string;createdAt:string;includesDatabase:boolean;includesConfiguration?:boolean;includesMail?:boolean;description:string}
export interface ProjectTask{id:string;projectId?:string;name:string;command:string;args:string[];category:'composer'|'node'|'framework'|'test'|'custom';safe:boolean;lastRunAt?:string;lastExitCode?:number}
export interface SecurityFinding{id:string;severity:'info'|'warning'|'critical';category:string;title:string;detail:string;fixable:boolean;projectId?:string;resolved:boolean}
export interface PluginInfo{id:string;name:string;description:string;category:'template'|'service'|'tool';version:string;enabled:boolean;installed:boolean;builtIn:boolean}
export interface RepairAction{id:string;label:string;status:'fixed'|'ok'|'warning'|'failed';detail:string}
export interface OfflineRuntimeState{status:'not-prepared'|'ready'|'incomplete';directory?:string;packages:number;requiredPackages:number;lastCheckedAt?:string}
export interface RuntimePackageInfo{id:string;name:string;version:string;file:string;sha256:string;actualSha256?:string;bytes:number;installed:boolean;verified:boolean;required:boolean;detail:string}
export interface ComponentPack{id:string;name:string;description:string;category:'webserver'|'database'|'mail'|'tool';status:'bundled'|'available-offline'|'installed'|'blocked'|'planned';requiresAdmin:boolean;license:string;version?:string;publisher?:string;verified?:boolean;path?:string}
export interface ProjectHealthCheck{id:string;label:string;status:HealthStatus;detail:string;fixable:boolean}
export interface ProjectHealthReport{projectId:string;projectName:string;domain:string;score:number;status:HealthStatus;checkedAt:string;checks:ProjectHealthCheck[]}
export interface SecretMetadata{id:string;key:string;projectId?:string;scope:'global'|'project';updatedAt:string;encryption:'windows-dpapi'|'test-codec'}
export interface PortConflictInfo{serviceId:ServiceId;serviceName:string;port:number;status:'free'|'localdeck'|'occupied';ownerPid?:number;ownerName?:string;ownerPath?:string;suggestedPort:number;checkedAt:string}
export interface ProductionParityCheck{id:string;label:string;status:HealthStatus;local:string;expected:string;detail:string}
export interface ProductionParityReport{projectId:string;projectName:string;score:number;status:HealthStatus;checkedAt:string;checks:ProductionParityCheck[]}
export interface PreflightStep{id:string;label:string;status:HealthStatus;detail:string;durationMs:number}
export interface PreflightReport{projectId:string;projectName:string;status:HealthStatus;startedAt:string;finishedAt:string;steps:PreflightStep[]}
export interface TestLabCheck{id:string;label:string;status:HealthStatus;detail:string}
export interface TestLabReport{projectId:string;projectName:string;url:string;status:HealthStatus;checkedAt:string;durationMs:number;checks:TestLabCheck[];screenshot?:string}
export interface DevDriveState{supported:boolean;drive:string;isDevDrive:boolean;status:'active'|'available'|'unsupported'|'error';detail:string;securityMode:string;checkedAt:string}
export interface CrashRecoveryState{sessionId:string;uncleanShutdownDetected:boolean;recoveredServices:ServiceId[];status:'clean'|'detected'|'recovering'|'recovered'|'failed';detail:string;checkedAt:string}
export interface AtomicUpdateState{status:'idle'|'staged'|'healthy'|'rollback-ready'|'failed';currentVersion:string;lastKnownGoodVersion:string;stagedVersion?:string;stagedFile?:string;checkedAt:string;detail:string}
export interface ReleaseReadinessCheck{id:string;label:string;status:HealthStatus;detail:string}
export interface ReleaseReadiness{score:number;status:HealthStatus;checkedAt:string;checks:ReleaseReadinessCheck[]}
export interface OperationStep{id:string;label:string;status:'pending'|'running'|'ok'|'warning'|'error'|'cancelled';detail:string;startedAt?:string;finishedAt?:string}
export interface OperationRecord{id:string;kind:'safe-change'|'rehearsal'|'release-gate'|'sbom'|'performance'|'browser-matrix'|'mail-quality'|'dependency-guard'|'worker'|'api'|'webhook'|'drift'|'migration'|'component-pack';title:string;status:'queued'|'running'|'completed'|'failed'|'cancelled';progress:number;message:string;projectId?:string;targetId?:string;startedAt:string;updatedAt:string;finishedAt?:string;canRetry:boolean;canCancel:boolean;steps:OperationStep[];metadata?:Record<string,string>}
export interface SafeChangeRecord{id:string;operationId:string;kind:'service-port'|'project-profile'|'settings';targetId:string;label:string;before:Record<string,unknown>;after:Record<string,unknown>;status:'checking'|'applied'|'rolled-back'|'failed';createdAt:string;completedAt?:string;rolledBackAt?:string;error?:string}
export interface StartProfile{id:string;name:string;description:string;services:ServiceId[];projectIds:string[];builtIn:boolean;active:boolean;updatedAt:string}
export interface ServiceDependency{serviceId:ServiceId;requires:ServiceId[];usedBy:ServiceId[];reason:string}
export interface PortBindingInfo{id:string;serviceId?:ServiceId;label:string;protocol:'TCP'|'UDP';family:'IPv4'|'IPv6';address:string;port:number;role:'primary'|'secondary'|'project'|'control';status:'free'|'reserved'|'localdeck'|'occupied';ownerPid?:number;ownerName?:string;ownerPath?:string;reservedBy:string;checkedAt:string}
export interface RuntimeLifecycleInfo{version:string;status:'current'|'security'|'legacy';usedBy:string[];installed:boolean;detail:string}
export interface EngineeringCheck{id:string;label:string;status:HealthStatus;detail:string;durationMs?:number}
export interface EngineeringReport{id:string;kind:'rehearsal'|'release-gate'|'sbom'|'performance'|'browser-matrix'|'mail-quality'|'dependency-guard'|'drift'|'migration'|'component-pack';projectId?:string;projectName?:string;title:string;status:HealthStatus;score:number;summary:string;createdAt:string;checks:EngineeringCheck[];artifacts:string[];metrics?:Record<string,number|string|boolean>}
export interface ApiEndpoint{id:string;method:'GET'|'POST'|'PUT'|'PATCH'|'DELETE'|'HEAD'|'OPTIONS';path:string;summary:string;requestBody?:string}
export interface ApiWorkspace{id:string;name:string;baseUrl:string;projectId?:string;sourceFile?:string;endpoints:ApiEndpoint[];createdAt:string;updatedAt:string}
export interface ApiRun{id:string;workspaceId:string;endpointId?:string;method:string;url:string;status?:number;durationMs:number;responsePreview:string;error?:string;ranAt:string}
export interface WebhookEndpoint{id:string;name:string;path:string;secret:string;enabled:boolean;createdAt:string}
export interface WebhookEvent{id:string;endpointId:string;method:string;headers:Record<string,string>;body:string;receivedAt:string;replayCount:number;lastReplayAt?:string}
export interface WorkerProcessInfo{id:string;projectId:string;name:string;command:string;args:string[];status:'stopped'|'starting'|'running'|'error';pid?:number;logs:string[];autoRestart:boolean;restartCount:number;startedAt?:string;stoppedAt?:string;error?:string}
export interface ReplayCapture{id:string;projectId?:string;name:string;method:string;url:string;headers:Record<string,string>;body:string;status?:number;durationMs?:number;createdAt:string;lastReplayedAt?:string}
export interface PhpRuntime{version:string;installed:boolean;active:boolean;path?:string}
export interface PhpExtension{id:string;label:string;enabled:boolean;available:boolean;description:string}
export interface InstallationState{status:'not-installed'|'installing'|'installed'|'failed';progress:number;message:string;startedAt?:string;finishedAt?:string}
export interface Diagnostic{id:string;label:string;status:'ok'|'warning'|'error';detail:string;fixable:boolean}
export interface UpdateState{status:UpdateStatus;currentVersion:string;latestVersion?:string;title?:string;notes?:string;downloadUrl?:string;sha256?:string;signed?:boolean;publisher?:string;publishedAt?:string;rollbackVersion?:string;rollbackUrl?:string;rollbackSha256?:string;error?:string;checkedAt?:string;showPopup?:boolean}
export interface AppSettings{simulationMode:boolean;startWithWindows:boolean;minimizeToTray:boolean;telemetry:boolean;privacyMode:boolean;language:AppLanguage;dataDirectory:string;projectsDirectory:string;folderMode:boolean;defaultPhpVersion:string;localDomainSuffix:LocalDomainSuffix;autoBackup:boolean;backupRetention:number;runtimeMode:RuntimeMode;serviceAutoStart:boolean;autoRestart:boolean;restoreServicesAfterCrash:boolean;atomicUpdates:boolean;autoUpdateCheck:boolean;updateChannel:'stable'|'beta';updateFeedUrl:string;firstRunComplete:boolean;backupSchedule:BackupSchedule;webControlEnabled:boolean;webControlPort:number;dnsMode:DnsMode;mailMode:MailMode;mailMaxMessages:number;mailMaxAgeDays:number;smtpHost:string;smtpPort:number;smtpUsername:string;requireSignedUpdates:boolean;trustedUpdatePublisher:string;trustedPackPublisher:string;combinedLogs:boolean;securityScanOnStart:boolean;resourceSaver:boolean;idleStopMinutes:number;lanSharingEnabled:boolean;mcpEnabled:boolean;offlineFirst:boolean}
export interface AppState{services:ServiceState[];projects:Project[];blueprints:ProjectBlueprint[];branchEnvironments:BranchEnvironment[];components:RuntimeComponent[];componentPacks:ComponentPack[];runtimePackages:RuntimePackageInfo[];projectHealth:ProjectHealthReport[];productionParity:ProductionParityReport[];preflightReports:PreflightReport[];testLabReports:TestLabReport[];secretVault:SecretMetadata[];portConflicts:PortConflictInfo[];portBindings:PortBindingInfo[];serviceDependencies:ServiceDependency[];startProfiles:StartProfile[];actionOperations:OperationRecord[];safeChanges:SafeChangeRecord[];runtimeLifecycle:RuntimeLifecycleInfo[];engineeringReports:EngineeringReport[];apiWorkspaces:ApiWorkspace[];apiRuns:ApiRun[];webhookEndpoints:WebhookEndpoint[];webhookEvents:WebhookEvent[];workers:WorkerProcessInfo[];replayCaptures:ReplayCapture[];devDrive:DevDriveState;crashRecovery:CrashRecoveryState;atomicUpdate:AtomicUpdateState;releaseReadiness:ReleaseReadiness;inspectorEvents:InspectorEvent[];resourceUsage:ResourceUsage;shares:ShareSession[];databases:DatabaseInfo[];mailAddresses:MailAddress[];backups:BackupInfo[];snapshots:SnapshotInfo[];tasks:ProjectTask[];securityFindings:SecurityFinding[];plugins:PluginInfo[];repairActions:RepairAction[];offlineRuntime:OfflineRuntimeState;phpVersions:PhpRuntime[];phpExtensions:PhpExtension[];installation:InstallationState;diagnostics:Diagnostic[];update:UpdateState;settings:AppSettings;logs:LogEntry[]}
export interface LogEntry{id:string;at:string;level:'info'|'success'|'warning'|'error';source:string;message:string}
export interface UpdateManifest{version:string;title?:string;notes?:string;downloadUrl:string;publishedAt?:string;channel?:'stable'|'beta';sha256:string;signed?:boolean;publisher?:string;rollbackVersion?:string;rollbackUrl?:string;rollbackSha256?:string}
