(function(){
 'use strict';
 var language='nl';
 var dictionary={
  'LocalDeck Webbeheer':'LocalDeck Web Management','LocalDeck Mailbeheer':'LocalDeck Mail Management','Beveiligd met een lokale sessietoken · alleen 127.0.0.1':'Protected by a local session token · 127.0.0.1 only','Verbinden…':'Connecting…','Je volledige lokale ontwikkelstack':'Your complete local development stack','Services, Project Capsules, databases, testmail en diagnose vanuit één webinterface.':'Services, Project Capsules, databases, test email and diagnostics from one web interface.','Alles starten':'Start all','Alles stoppen':'Stop all','Mailbeheer ↗':'Mail Management ↗',
  'Projecten':'Projects','Productiepariteit, lokale CI, Testlab en IDE':'Production parity, local CI, Test Lab and IDE','Databases':'Databases','Aanmaken, bekijken en veilig verwijderen':'Create, view and safely delete','Aanmaken':'Create','Test-mailadressen':'Test email addresses','Mailpit vangt berichten voor ieder adres op':'Mailpit captures messages for every address','Omschrijving':'Description','Toevoegen':'Add','Prestaties & integraties':'Performance & integrations','Instellingen worden direct lokaal opgeslagen':'Settings are stored locally immediately','Meten…':'Measuring…','Eco-modus':'Eco mode','Stop na inactiviteit':'Stop after inactivity','Nooit':'Never','15 minuten':'15 minutes','30 minuten':'30 minutes','1 uur':'1 hour','Offline eerst':'Offline first','Geen stille downloads':'No silent downloads','LAN-delen':'LAN sharing','Internetdeling blijft uit':'Internet sharing remains off','Lokale MCP':'Local MCP','Expliciete tools':'Explicit tools','Crashherstel':'Crash recovery','Herstel services':'Restore services','Atomische updates':'Atomic updates','Rollback gereed':'Rollback ready',
  'DPAPI-versleuteld; waarden worden nooit teruggestuurd':'DPAPI encrypted; values are never returned','LOKAAL':'LOCAL','Geheime waarde':'Secret value','Globaal':'Global','Versleuteld opslaan':'Store encrypted','Herstelstatus':'Recovery status','Crashherstel, updates en Windows Dev Drive':'Crash recovery, updates and Windows Dev Drive','Dev Drive controleren':'Check Dev Drive','Developer Inspector':'Developer Inspector','Recente lokale requests, taken, database- en runtimegebeurtenissen':'Recent local requests, tasks, database and runtime events','Nu meten':'Measure now','Nog geen projecten.':'No projects yet.','Nog geen databases.':'No databases yet.','Nog geen adressen.':'No addresses yet.','Lokaal testadres':'Local test address','Verwijder':'Delete','Pariteit':'Parity','processen':'processes','Klik op Nu meten.':'Click Measure now.','Nieuwe poort:':'New port:','Deze poort hoort bij LocalDeck.':'This port belongs to LocalDeck.','Deze poort is vrij.':'This port is available.','Database verwijderen?':'Delete database?','Geheime waarde verwijderen?':'Delete secret value?','Opdracht mislukt':'Command failed','Windows-services':'Windows services','App-modus':'App mode','ACTIEF':'RUNNING','GESTOPT':'STOPPED','ONTBREEKT':'MISSING','POORT':'PORT',
  'Mailbeheer Pro':'Mail Management Pro','Lokale inboxen, virtuele adressen, bronweergave en kwaliteitscontrole zonder account.':'Local inboxes, virtual addresses, source view and quality checks without an account.','Overzicht':'Overview','Nieuwe testmail':'New test email','Totaal':'Total','Ongelezen':'Unread','SMTP':'SMTP','Postvakken':'Mailboxes','Alle berichten':'All messages','Virtuele adressen':'Virtual addresses','Nieuw adres':'New address','Adres toevoegen':'Add address','Tags':'Tags','Zoek afzender, ontvanger, onderwerp of inhoud…':'Search sender, recipient, subject or content…','Alle status':'All statuses','Gelezen':'Read','Laden…':'Loading…','Verwijder':'Delete','Leeg':'Empty','Pagina 1':'Page 1','Selecteer een bericht':'Select a message','Bekijk HTML, platte tekst, headers en de volledige bron.':'View HTML, plain text, headers and the full source.','Stuur direct een bericht naar de lokale Mailpit-inbox.':'Send a message directly to the local Mailpit inbox.','Van':'From','Aan':'To','Onderwerp':'Subject','Bericht':'Message','Testbericht vanuit LocalDeck':'Test message from LocalDeck','Dit is een lokaal testbericht vanuit LocalDeck Mailbeheer.':'This is a local test message from LocalDeck Mail Management.','Versturen':'Send','Onbekend':'Unknown',
  'Mailpit staat uit':'Mailpit is stopped','Start de service om je lokale inboxen en testmail te beheren.':'Start the service to manage your local inboxes and test email.','De ingebouwde Mailpit-runtime ontbreekt.':'The built-in Mailpit runtime is missing.','Mailpit starten':'Start Mailpit','Naar overzicht':'Back to overview','Mailpit wordt gestart…':'Mailpit is starting…','Nog geen tags.':'No tags yet.','Nog geen adressen.':'No addresses yet.','Dit postvak is leeg':'This mailbox is empty','Nieuwe testmail verschijnt hier automatisch.':'New test email appears here automatically.','geen onderwerp':'no subject','geselecteerd':'selected','bericht':'message','berichten':'messages','Markeer ongelezen':'Mark unread','Verwijder bericht':'Delete message','Grootte':'Size','Tekst':'Text','Bron':'Source','externe afbeeldingen':'external images','Bijlage':'Attachment','Dit bericht bevat geen platte tekst.':'This message contains no plain text.','Bron wordt geladen…':'Loading source…','Geen headers gevonden.':'No headers found.','Gemarkeerd als gelezen.':'Marked as read.','Gemarkeerd als ongelezen.':'Marked as unread.','Bericht verwijderd.':'Message deleted.','Geselecteerde berichten verwijderd.':'Selected messages deleted.','Tags bijgewerkt.':'Tags updated.','Postvak geleegd.':'Mailbox emptied.','Virtueel adres toegevoegd.':'Virtual address added.','Adres uit het adresboek verwijderd.':'Address removed from the address book.','Testmail ontvangen in Mailpit.':'Test email received in Mailpit.','Uit adresboek verwijderen':'Remove from address book'
 };
 var patterns=[[/^Pagina (\d+) van (\d+)$/,function(m){return'Page '+m[1]+' of '+m[2]}],[/^(\d+) geselecteerd$/,function(m){return m[1]+' selected'}],[/^(\d+) bericht$/,function(m){return m[1]+' message'}],[/^(\d+) berichten$/,function(m){return m[1]+' messages'}],[/^(\d+) ontvangen berichten$/,function(m){return m[1]+' received messages'}]];
 function translate(value){if(language!=='en'||!value)return value;var source=String(value),leading=(source.match(/^\s*/)||[''])[0],trailing=(source.match(/\s*$/)||[''])[0],core=source.trim(),result=dictionary[core];if(!result)for(var i=0;i<patterns.length;i++){var match=core.match(patterns[i][0]);if(match){result=patterns[i][1](match);break}}return leading+(result||core)+trailing}
 var textMemory=new WeakMap(),attributeMemory=new WeakMap();
 function skip(node){return node.parentElement&&node.parentElement.closest('script,style,code,pre,textarea,iframe,[translate="no"],[data-no-translate]')}
 function textNode(node){if(skip(node))return;var current=node.data,known=textMemory.get(node),source=known&&current===known.rendered?known.source:current,rendered=translate(source);textMemory.set(node,{source:source,rendered:rendered});if(current!==rendered)node.data=rendered}
 function attrs(element){if(element.closest&&element.closest('[translate="no"],[data-no-translate]'))return;var values=attributeMemory.get(element);if(!values){values={};attributeMemory.set(element,values)}['title','aria-label','placeholder'].forEach(function(name){var current=element.getAttribute&&element.getAttribute(name);if(current===null||current===undefined)return;var known=values[name],source=known&&current===known.rendered?known.source:current,rendered=translate(source);values[name]={source:source,rendered:rendered};if(current!==rendered)element.setAttribute(name,rendered)})}
 function render(root){if(root.nodeType===3){textNode(root);return}if(root.nodeType!==1&&root.nodeType!==9&&root.nodeType!==11)return;if(root.nodeType===1)attrs(root);var walker=document.createTreeWalker(root,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT),node=walker.nextNode();while(node){if(node.nodeType===3)textNode(node);else attrs(node);node=walker.nextNode()}}
 var originalConfirm=window.confirm.bind(window),originalPrompt=window.prompt.bind(window),originalAlert=window.alert.bind(window);window.confirm=function(message){return originalConfirm(translate(message))};window.prompt=function(message,value){return originalPrompt(translate(message),value)};window.alert=function(message){return originalAlert(translate(message))};
 window.ldT=translate;window.ldLocale=function(){return language==='en'?'en-US':'nl-NL'};
 function setLanguage(next){next=next==='en'?'en':'nl';if(next===language&&document.documentElement.lang===next)return;language=next;document.documentElement.lang=next;render(document.body)}
 var observer=new MutationObserver(function(records){records.forEach(function(record){if(record.type==='characterData')textNode(record.target);else{record.addedNodes.forEach(render);if(record.type==='attributes')attrs(record.target)}})});observer.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['title','aria-label','placeholder']});
 function sync(){fetch('/api/state',{cache:'no-store'}).then(function(response){return response.json()}).then(function(state){setLanguage(state.settings&&state.settings.language)}).catch(function(){})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){render(document.body);sync()});else{render(document.body);sync()}setInterval(sync,5000);
})();
