import{useMemo,useState}from'react';
import{Activity,AlertTriangle,ArrowRight,Beaker,Boxes,Braces,CheckCircle2,ChevronDown,ChevronRight,Clipboard,Clock3,DatabaseZap,FileJson,FlaskConical,Gauge,GitCompareArrows,Globe2,Inbox,Network,PackageCheck,Play,Plus,Power,RefreshCw,RotateCcw,Route,ServerCog,ShieldCheck,Square,Terminal,Trash2,Webhook,XCircle,Zap}from'lucide-react';
import type{StateAction}from'./ControlCenter';
import{localeFor}from'./i18n';

const statusLabel=(status:string)=>status==='ok'||status==='completed'?'Geslaagd':status==='running'?'Bezig':status==='error'||status==='failed'?'Mislukt':status==='warning'?'Aandacht':status==='cancelled'?'Geannuleerd':status==='localdeck'?'Actief':status==='occupied'?'Bezet':'Gereserveerd';
const localTime=(value?:string)=>value?new Date(value).toLocaleString(localeFor()):'—';

export function ActionCenterPage({state,action}:{state:AppState;action:StateAction}){
 const operations=state.actionOperations,safeByOperation=useMemo(()=>new Map(state.safeChanges.map(change=>[change.operationId,change])),[state.safeChanges]);
 return <><section className="featureHero actionHero"><div><span className="eyebrow"><Activity/>ACTION CENTER</span><h2>Elke belangrijke actie blijft controleerbaar</h2><p>Voortgang, deelstappen, fouten en herstelpunten blijven bewaard, ook na een herstart van LocalDeck.</p></div><button className="ghost big" disabled={!operations.some(item=>item.status!=='running'&&item.status!=='queued')} onClick={()=>action(()=>window.localdeck.clearCompletedOperations())}><Trash2/>Afgeronde acties wissen</button></section>
  <section className="actionCenterList">{operations.map(operation=>{const safe=safeByOperation.get(operation.id),open=operation.status==='running'||operation.status==='failed';return <details className={`panel actionRecord ${operation.status}`} open={open} key={operation.id}><summary><span className="actionKind"><OperationIcon status={operation.status}/></span><span><b>{operation.title}</b><small>{operation.message}</small></span><span className="actionMeta"><em>{statusLabel(operation.status)}</em><small>{operation.progress}% · {localTime(operation.updatedAt)}</small></span><ChevronDown/></summary><div className="actionProgress" aria-label={`${operation.progress} procent`}><span style={{width:`${operation.progress}%`}}/></div><div className="operationSteps">{operation.steps.map(step=><div className={step.status} key={step.id}><OperationIcon status={step.status}/><span><b>{step.label}</b><small>{step.detail}</small></span></div>)}</div><div className="toolbar actionRecordTools">{operation.canCancel&&<button className="ghost" onClick={()=>action(()=>window.localdeck.cancelOperation(operation.id))}><Square/>Annuleren</button>}{operation.canRetry&&['failed','cancelled'].includes(operation.status)&&<button className="primary" onClick={()=>action(()=>window.localdeck.retryOperation(operation.id))}><RefreshCw/>Opnieuw</button>}{safe&&['applied','failed'].includes(safe.status)&&<button className="ghost warningButton" onClick={()=>action(()=>window.localdeck.rollbackSafeChange(safe.id))}><RotateCcw/>Terugdraaien</button>}{operation.status!=='running'&&operation.status!=='queued'&&<button className="iconButton danger" aria-label="Actie uit lijst verwijderen" onClick={()=>action(()=>window.localdeck.dismissOperation(operation.id))}><Trash2/></button>}</div></details>})}{!operations.length&&<section className="panel emptyState"><Activity/><h3>Nog geen acties</h3><p>Rehearsals, releasecontroles, poortwijzigingen en workers verschijnen hier automatisch.</p></section>}</section></>;
}

function OperationIcon({status}:{status:string}){return status==='ok'||status==='completed'?<CheckCircle2/>:status==='error'||status==='failed'?<XCircle/>:status==='warning'?<AlertTriangle/>:status==='running'?<RefreshCw className="spin"/>:status==='cancelled'?<Square/>:<Clock3/>}

export function AutomationPage({state,action}:{state:AppState;action:StateAction}){
 const[name,setName]=useState(''),[selectedServices,setSelectedServices]=useState<ServiceId[]>(['php','apache']),[projectId,setProjectId]=useState(state.projects[0]?.id||''),[workerName,setWorkerName]=useState('Queue worker'),[command,setCommand]=useState('php'),[args,setArgs]=useState('artisan queue:work --tries=1');
 const toggleSelected=(id:ServiceId)=>setSelectedServices(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
 const addProfile=async()=>{if(!name)return;const saved=await action(()=>window.localdeck.saveStartProfile({name,services:selectedServices}));if(saved)setName('')};
 const addWorker=async()=>{if(!projectId||!workerName||!command)return;const saved=await action(()=>window.localdeck.saveWorker({projectId,name:workerName,command,args:args.trim()?args.trim().split(/\s+/):[],autoRestart:true}));if(saved)setWorkerName('Queue worker')};
 return <><section className="featureHero automationHero"><div><span className="eyebrow"><ServerCog/>AUTOMATION & SERVICES</span><h2>Start precies wat een werkdag nodig heeft</h2><p>Profielen respecteren service-afhankelijkheden. Workers draaien verborgen, zonder DOS-venster, en stoppen mee met LocalDeck.</p></div><button className="primary big" onClick={()=>action(()=>window.localdeck.inspectAllPorts())}><Network/>Port Autopilot 2 controleren</button></section>
  <section className="panel full"><div className="panelHead"><div><h3>Startprofielen</h3><p>Een profiel start vereisten automatisch en stopt services die niet bij het profiel horen.</p></div><Power/></div><div className="startProfileGrid">{state.startProfiles.map(profile=><article className={profile.active?'active':''} key={profile.id}><span className="profileStatus">{profile.active?'ACTIEF':profile.builtIn?'INGEBOUWD':'EIGEN'}</span><h4>{profile.name}</h4><p>{profile.description}</p><div className="servicePills">{profile.services.map(id=><span key={id}>{state.services.find(item=>item.id===id)?.name||id}</span>)}</div><div className="toolbar"><button className="primary" onClick={()=>action(()=>window.localdeck.applyStartProfile(profile.id))}><Play/>Toepassen</button>{!profile.builtIn&&<button className="iconButton danger" aria-label="Startprofiel verwijderen" onClick={()=>action(()=>window.localdeck.deleteStartProfile(profile.id))}><Trash2/></button>}</div></article>)}</div><div className="profileBuilder"><input value={name} onChange={event=>setName(event.target.value)} placeholder="Naam eigen profiel"/><div className="checkPills">{state.services.map(service=><label key={service.id}><input type="checkbox" checked={selectedServices.includes(service.id)} onChange={()=>toggleSelected(service.id)}/><span>{service.name}</span></label>)}</div><button className="ghost" disabled={!name||!selectedServices.length} onClick={addProfile}><Plus/>Profiel opslaan</button></div></section>
  <section className="twoCol"><section className="panel"><div className="panelHead"><div><h3>Afhankelijkheidsgrafiek</h3><p>LocalDeck start vereisten eerst en stopt gebruikers vóór hun onderliggende service.</p></div><Route/></div><div className="dependencyList">{state.serviceDependencies.map(item=><div key={item.serviceId}><b>{state.services.find(service=>service.id===item.serviceId)?.name||item.serviceId}</b><ChevronRight/><span>{item.requires.length?item.requires.map(id=>state.services.find(service=>service.id===id)?.name||id).join(' + '):'Zelfstandig'}</span><small>{item.reason}</small></div>)}</div></section>
   <section className="panel"><div className="panelHead"><div><h3>PHP lifecycle</h3><p>Projectgebruik en upgradeprioriteit in één overzicht.</p></div><Braces/></div><div className="lifecycleList">{state.runtimeLifecycle.map(item=><div className={item.status} key={item.version}><b>PHP {item.version}</b><span>{item.status==='current'?'Actueel':item.status==='security'?'Beveiligingslijn':'Legacy'}</span><small>{item.usedBy.length?`Gebruikt door ${item.usedBy.join(', ')}.`:'Nog niet aan een project gekoppeld.'} {item.detail}</small></div>)}</div></section>
  </section>
  <section className="panel full"><div className="panelHead"><div><h3>Port Autopilot 2.0</h3><p>Primaire en secundaire bindingen, TCP/UDP, IPv4/IPv6, reserveringen en proceseigenaren.</p></div><Network/></div>{state.portBindings.length?<div className="bindingTable"><div className="bindingHeader"><b>Binding</b><b>Protocol</b><b>Poort</b><b>Status/eigenaar</b></div>{state.portBindings.map(item=><div key={item.id}><span><b>{item.label}</b><small>{item.address} · {item.role}</small></span><code>{item.protocol}/{item.family}</code><strong>{item.port}</strong><span className={item.status}><b>{statusLabel(item.status)}</b><small>{item.ownerName?`${item.ownerName}${item.ownerPid?` · PID ${item.ownerPid}`:''}`:`Gereserveerd door ${item.reservedBy}`}</small></span></div>)}</div>:<p className="emptyInline">Klik op Port Autopilot 2 controleren om alle bindingen te inventariseren.</p>}</section>
  <section className="panel full"><div className="panelHead"><div><h3>Queues & schedulers</h3><p>Langlopende projectprocessen starten verborgen en bewaren hun laatste uitvoer.</p></div><Terminal/></div><div className="workerBuilder"><select value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">Kies project</option>{state.projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select><input value={workerName} onChange={event=>setWorkerName(event.target.value)} placeholder="Workernaam"/><input value={command} onChange={event=>setCommand(event.target.value)} placeholder="php"/><input value={args} onChange={event=>setArgs(event.target.value)} placeholder="artisan queue:work --tries=1"/><button className="ghost" disabled={!projectId||!workerName||!command} onClick={addWorker}><Plus/>Worker toevoegen</button></div><div className="workerList">{state.workers.map(worker=><article className={worker.status} key={worker.id}><span className="workerIcon"><Terminal/></span><div><b>{worker.name}</b><code>{worker.command} {worker.args.join(' ')}</code><small>{worker.status==='running'?`Draait verborgen · PID ${worker.pid}`:worker.error||`Gestopt${worker.stoppedAt?` · ${localTime(worker.stoppedAt)}`:''}`}</small>{worker.logs[0]&&<pre>{worker.logs[0]}</pre>}</div>{worker.status==='running'?<button className="ghost" onClick={()=>action(()=>window.localdeck.stopWorker(worker.id))}><Square/>Stop</button>:<button className="primary" onClick={()=>action(()=>window.localdeck.startWorker(worker.id))}><Play/>Start</button>}<button className="iconButton danger" aria-label="Worker verwijderen" onClick={()=>action(()=>window.localdeck.deleteWorker(worker.id))}><Trash2/></button></article>)}</div></section>
 </>;
}

export function QualityLabPage({state,action}:{state:AppState;action:StateAction}){
 const[projectId,setProjectId]=useState(state.projects[0]?.id||''),project=state.projects.find(item=>item.id===projectId),reports=state.engineeringReports.filter(item=>!item.projectId||item.projectId===projectId).slice(0,12);
 const tools=[
  {id:'rehearsal',title:'Rehearsal Mode',description:'Kopieert het project tijdelijk, controleert locks, syntax, migraties en tests zonder de bron te wijzigen.',icon:FlaskConical,run:()=>window.localdeck.runRehearsal(projectId)},
  {id:'release',title:'Release Gate',description:'Combineert preflight, dependencies, drift, SBOM, performance en browserresultaten tot één besluit.',icon:ShieldCheck,run:()=>window.localdeck.runReleaseGate(projectId)},
  {id:'performance',title:'Performancebaseline',description:'Meet vijf lokale requests en markeert regressies ten opzichte van de vorige baseline.',icon:Gauge,run:()=>window.localdeck.runPerformanceBaseline(projectId)},
  {id:'browser',title:'Browsermatrix',description:'Rendert desktop, tablet en mobiel in Chromium en bewaart controleerbare screenshots.',icon:Globe2,run:()=>window.localdeck.runBrowserMatrix(projectId)},
  {id:'dependency',title:'Dependency Guard',description:'Voert Composer validate/audit uit en controleert reproduceerbare PHP- en Node-lockfiles.',icon:PackageCheck,run:()=>window.localdeck.runDependencyGuard(projectId)},
  {id:'sbom',title:'SBOM & licenties',description:'Genereert lokaal een CycloneDX 1.5-inventaris uit Composer- en Node-lockfiles.',icon:Boxes,run:()=>window.localdeck.generateSbom(projectId)},
  {id:'migration',title:'DB Migration Lab',description:'Leest migratiestatus en risico’s zonder een schemawijziging uit te voeren.',icon:DatabaseZap,run:()=>window.localdeck.runMigrationLab(projectId)},
  {id:'drift',title:'Team Drift Detector',description:'Vergelijkt werkmap, Project Capsule, lockfile en toegewezen PHP-runtime.',icon:GitCompareArrows,run:()=>window.localdeck.runDriftDetector(projectId)}
 ];
 return <><section className="featureHero qualityHero"><div><span className="eyebrow"><Beaker/>QUALITY & RELEASE LAB</span><h2>Van lokale wijziging naar aantoonbaar releasegereed</h2><p>Alle controles blijven offline en lokaal; elke uitvoering verschijnt met stappen in het Action Center.</p></div><select aria-label="Actief kwaliteitsproject" value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">Kies project</option>{state.projects.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></section>
  <div className="qualityToolGrid">{tools.map(tool=><article className="panel" key={tool.id}><tool.icon/><div><h3>{tool.title}</h3><p>{tool.description}</p></div><button className={tool.id==='release'?'primary':'ghost'} disabled={!project} onClick={()=>action(tool.run)}><Play/>Start</button></article>)}</div>
  <section className="twoCol"><section className="panel"><div className="panelHead"><div><h3>Mail Quality Lab</h3><p>Beoordeelt onderwerp, afzender, ontvangers, inhoud en bijlagen van de nieuwste lokale mail.</p></div><Inbox/></div><button className="primary" onClick={()=>action(()=>window.localdeck.runMailQuality())}><Play/>Laatste mail controleren</button></section><section className="panel"><div className="panelHead"><div><h3>Windows & componenten</h3><p>Controleer Dev Drive en inspecteer een .ldpack zonder het archief uit te pakken.</p></div><ServerCog/></div><div className="toolbar"><button className="ghost" onClick={()=>action(()=>window.localdeck.detectDevDrive())}><RefreshCw/>Dev Drive-assistent</button><button className="ghost" onClick={()=>action(()=>window.localdeck.inspectComponentPack())}><PackageCheck/>Pack inspecteren</button></div><small>{state.devDrive.detail}</small></section></section>
  <section className="panel full"><div className="panelHead"><div><h3>Recente kwaliteitsrapporten</h3><p>{project?project.name:'Alle algemene controles'} · auditbaar en lokaal opgeslagen.</p></div><FileJson/></div><div className="reportList">{reports.map(report=><details key={report.id}><summary><span className={report.status}><OperationIcon status={report.status}/></span><span><b>{report.title}</b><small>{report.summary}</small></span><strong>{report.score}/100</strong><ChevronDown/></summary><div>{report.checks.map(check=><article className={check.status} key={check.id}><OperationIcon status={check.status}/><span><b>{check.label}</b><small>{check.detail}</small></span></article>)}</div>{report.artifacts.length>0&&<small className="artifactLine">{report.artifacts.length} lokaal rapportbestand{report.artifacts.length===1?'':'en'} opgeslagen.</small>}</details>)}{!reports.length&&<p className="emptyInline">Start een kwaliteitscontrole om het eerste rapport te maken.</p>}</div></section>
 </>;
}

export function ApiStudioPage({state,action}:{state:AppState;action:StateAction}){
 const[workspaceId,setWorkspaceId]=useState(state.apiWorkspaces[0]?.id||''),[endpointId,setEndpointId]=useState(''),[body,setBody]=useState('{}'),[apiName,setApiName]=useState('Mijn lokale API'),[baseUrl,setBaseUrl]=useState('http://localhost'),[hookName,setHookName]=useState('Nieuwe webhook'),[targetUrl,setTargetUrl]=useState('http://localhost'),[captureName,setCaptureName]=useState('Handmatige request'),[captureMethod,setCaptureMethod]=useState('POST');
 const workspace=state.apiWorkspaces.find(item=>item.id===workspaceId),endpoint=workspace?.endpoints.find(item=>item.id===endpointId)||workspace?.endpoints[0],runs=state.apiRuns.filter(item=>item.workspaceId===workspaceId).slice(0,10),hookBase=`http://127.0.0.1:${state.settings.webControlPort}`;
 const createWorkspace=async()=>{const saved=await action(()=>window.localdeck.saveApiWorkspace({name:apiName,baseUrl}));if(saved)setApiName('Mijn lokale API')};
 const makeFixture=async()=>{if(!workspace||!endpoint)return;try{setBody(await window.localdeck.generateApiFixture(workspace.id,endpoint.id))}catch{setBody('{}')}};
 return <><section className="featureHero apiHero"><div><span className="eyebrow"><Webhook/>API, WEBHOOKS & REPLAY</span><h2>Lokale integraties testen zonder externe dienst</h2><p>Importeer OpenAPI, voer alleen lokale requests uit, vang webhooks op en speel veilige requestopnames opnieuw af.</p></div><button className="primary big" onClick={()=>action(()=>window.localdeck.importApiWorkspace())}><FileJson/>OpenAPI importeren</button></section>
  <section className="twoCol apiColumns"><section className="panel"><div className="panelHead"><div><h3>API Studio</h3><p>OpenAPI 3 JSON/YAML of een handmatige lokale basis-URL.</p></div><Braces/></div><div className="apiBuilder"><input value={apiName} onChange={event=>setApiName(event.target.value)} placeholder="Werkruimtenaam"/><input value={baseUrl} onChange={event=>setBaseUrl(event.target.value)} placeholder="http://localhost:8080"/><button className="ghost" onClick={createWorkspace}><Plus/>Werkruimte</button></div><label className="fieldLabel">Werkruimte<select value={workspaceId} onChange={event=>{setWorkspaceId(event.target.value);setEndpointId('')}}><option value="">Kies werkruimte</option>{state.apiWorkspaces.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{workspace?<><label className="fieldLabel">Endpoint<select value={endpoint?.id||''} onChange={event=>setEndpointId(event.target.value)}><option value="">Kies endpoint</option>{workspace.endpoints.map(item=><option key={item.id} value={item.id}>{item.method} {item.path} · {item.summary}</option>)}</select></label><textarea className="codeArea" value={body} onChange={event=>setBody(event.target.value)} aria-label="JSON request body"/><div className="toolbar"><button className="ghost" disabled={!endpoint} onClick={makeFixture}><Zap/>Testdata</button><button className="primary" disabled={!endpoint} onClick={()=>endpoint&&action(()=>window.localdeck.runApiRequest(workspace.id,endpoint.id,body))}><Play/>Request</button><button className="iconButton danger" aria-label="API-werkruimte verwijderen" onClick={()=>action(()=>window.localdeck.deleteApiWorkspace(workspace.id))}><Trash2/></button></div><div className="apiRuns">{runs.map(run=><div className={run.error?'error':run.status&&run.status>=400?'warning':'ok'} key={run.id}><b>{run.method} · {run.status||'ERR'}</b><span>{run.durationMs} ms</span><small>{run.error||run.responsePreview.slice(0,180)||'Lege respons'}</small></div>)}</div></>:<p className="emptyInline">Importeer OpenAPI of maak een handmatige werkruimte.</p>}</section>
   <section className="panel"><div className="panelHead"><div><h3>Webhook Catcher</h3><p>Endpoint luistert alleen op 127.0.0.1 en heeft geen account of activatie nodig.</p></div><Webhook/></div><div className="inlineForm"><input value={hookName} onChange={event=>setHookName(event.target.value)} placeholder="Webhooknaam"/><button className="ghost" onClick={()=>action(()=>window.localdeck.createWebhookEndpoint(hookName))}><Plus/>Aanmaken</button></div><div className="hookList">{state.webhookEndpoints.map(hook=><article key={hook.id}><span><b>{hook.name}</b><code>{hookBase}{hook.path}</code></span><button className="iconButton" aria-label="Webhook-URL kopiëren" onClick={()=>void navigator.clipboard.writeText(`${hookBase}${hook.path}`)}><Clipboard/></button><button className="iconButton danger" aria-label="Webhook verwijderen" onClick={()=>action(()=>window.localdeck.deleteWebhookEndpoint(hook.id))}><Trash2/></button></article>)}</div><label className="fieldLabel">Lokale replaybestemming<input value={targetUrl} onChange={event=>setTargetUrl(event.target.value)} placeholder="http://project.localhost/webhook"/></label><div className="webhookEvents">{state.webhookEvents.slice(0,12).map(event=>{const hook=state.webhookEndpoints.find(item=>item.id===event.endpointId);return <article key={event.id}><span><b>{event.method} · {hook?.name||'Webhook'}</b><small>{localTime(event.receivedAt)} · {event.body.length} tekens · {event.replayCount} replays</small><code>{event.body.slice(0,180)||'(lege body)'}</code></span><button className="ghost" onClick={()=>action(()=>window.localdeck.replayWebhook(event.id,targetUrl))}><RotateCcw/>Replay</button></article>})}{!state.webhookEvents.length&&<p className="emptyInline">Nog geen webhooks ontvangen.</p>}</div></section></section>
  <section className="panel full"><div className="panelHead"><div><h3>LocalDeck Replay</h3><p>Bewaar een lokale requestopname zonder autorisatieheaders of cookies en speel hem later opnieuw af.</p></div><RotateCcw/></div><div className="replayBuilder"><input value={captureName} onChange={event=>setCaptureName(event.target.value)} placeholder="Naam"/><select value={captureMethod} onChange={event=>setCaptureMethod(event.target.value)}><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select><input value={targetUrl} onChange={event=>setTargetUrl(event.target.value)} placeholder="http://localhost/api"/><button className="ghost" onClick={()=>action(()=>window.localdeck.saveReplayCapture({name:captureName,method:captureMethod,url:targetUrl,headers:{'content-type':'application/json'},body,status:undefined,durationMs:undefined}))}><Plus/>Opname bewaren</button></div><div className="replayList">{state.replayCaptures.map(capture=><article key={capture.id}><Route/><span><b>{capture.name}</b><code>{capture.method} {capture.url}</code><small>{capture.lastReplayedAt?`${capture.status||'—'} · ${capture.durationMs||0} ms · ${localTime(capture.lastReplayedAt)}`:'Nog niet afgespeeld'}</small></span><button className="primary" onClick={()=>action(()=>window.localdeck.runReplayCapture(capture.id))}><Play/>Replay</button><button className="iconButton danger" aria-label="Replay-opname verwijderen" onClick={()=>action(()=>window.localdeck.deleteReplayCapture(capture.id))}><Trash2/></button></article>)}</div></section>
 </>;
}
