export type UiLanguage='nl'|'en';

let activeLanguage:UiLanguage='nl';

const english:Record<string,string>={
 'Overzicht':'Overview','Projecten':'Projects','Project Studio':'Project Studio','Services':'Services','Automatisering':'Automation','Action Center':'Action Center','Quality Lab':'Quality Lab','API & Webhooks':'API & Webhooks','Databases':'Databases','Snapshots':'Snapshots','Taken':'Tasks','E-mail':'Email','Product Doctor':'Product Doctor','Beveiliging':'Security','Catalogus':'Catalog','Installatie':'Installation','Inspector':'Inspector','Logboek':'Activity log','Instellingen':'Settings',
 'Alles instellen en bedienen vanuit één werkplek.':'Configure and control everything from one workspace.','Projectprofielen, domeinen, isolatie, PHP en Composer.':'Project profiles, domains, isolation, PHP and Composer.','Git, blueprints, branchomgevingen en reproduceerbare runtimes.':'Git, blueprints, branch environments and reproducible runtimes.','Kies app-modus of echte Windows-services.':'Choose app mode or real Windows services.','Startprofielen, afhankelijkheden, poortbindingen, queues en schedulers.':'Start profiles, dependencies, port bindings, queues and schedulers.','Duurzame voortgang, resultaten, herstelpunten, annuleren en opnieuw uitvoeren.':'Persistent progress, results, restore points, cancellation and retries.','Rehearsals, release gates, performance, browser-, dependency- en migratiecontroles.':'Rehearsals, release gates, performance, browser, dependency and migration checks.','OpenAPI, lokale requests, testdata, webhookopvang en reproduceerbare replays.':'OpenAPI, local requests, test data, webhook capture and reproducible replays.','Databases, tabellen, veilige SQL, gebruikers, import, export en back-ups.':'Databases, tables, safe SQL, users, imports, exports and backups.','Herstelpunten voor projectbestanden en gekoppelde databases.':'Restore points for project files and linked databases.','Composer-, Node-, test- en eigen projectopdrachten.':'Composer, Node, test and custom project commands.','Lokale testadressen, Mailbeheer Pro en configureerbare SMTP-routes.':'Local test addresses, Mail Management Pro and configurable SMTP routes.','Projectgezondheid, werkruimte-overdracht en releasegereedheid.':'Project health, workspace transfer and release readiness.','Lokale controles, automatisch herstel en updatevertrouwen.':'Local checks, automatic repair and trusted updates.','Templates, adapters, migratie en overdraagbare profielen.':'Templates, adapters, migration and portable profiles.','Ingebouwde offline runtime, PHP-versies, extensies en herstel.':'Built-in offline runtime, PHP versions, extensions and repair.','Requests, PHP, SQL, Xdebug, delen en resourcegebruik in één tijdlijn.':'Requests, PHP, SQL, Xdebug, sharing and resource usage in one timeline.','Doorzoek gebeurtenissen en gecombineerde servicelogs.':'Search events and combined service logs.','Gedrag, domeinen, updates, back-ups, privacy en webbeheer.':'Behavior, domains, updates, backups, privacy and web management.',
 'Windows development':'Windows development','Windows Preview':'Windows Preview','Uitvoermodus':'Run mode','UITVOERMODUS':'RUN MODE','APP-MODUS':'APP MODE','WINDOWS-SERVICE':'WINDOWS SERVICE','Alles gestopt':'All stopped','actief':'running','services actief':'services running','mapmodus':'folder mode','Privacy':'Privacy','Privacy aan':'Privacy on','Presentatie-/privacymodus':'Presentation/privacy mode','Websites-map':'Websites folder','Webbeheer':'Web management','Nieuw project':'New project','Nieuw project aanmaken':'Create new project','Melding sluiten':'Close notification',
 'Alle services starten':'Start all services','Alle services stoppen':'Stop all services','Port Autopilot 2 uitvoeren':'Run Port Autopilot 2','Webbeheer openen':'Open Web Management','Opdrachten zoeken':'Search commands','Zoek pagina of actie…':'Search page or action…',"PAGINA'S":'PAGES','SNELLE ACTIES':'QUICK ACTIONS','Geen opdrachten gevonden.':'No commands found.','projecten':'projects',
 'Importeer XAMPP':'Import XAMPP','Project of template':'Project or template','lokale projecten':'local projects','lokale omgevingen':'local environments','Webserver en virtuele hosts':'Web server and virtual hosts','Geïsoleerde FastCGI-pools':'Isolated FastCGI pools','Lokale databaseserver':'Local database server','Lokale e-mailopvang':'Local email capture','Cache en queues':'Cache and queues',
 'Project toevoegen':'Add project','Koppel een map aan een domein, PHP-versie en workflow.':'Link a folder to a domain, PHP version and workflow.','Projecttype':'Project type','Nieuwe PHP-website (offline)':'New PHP website (offline)','Bestaande website/map koppelen':'Link an existing website/folder','Projectnaam':'Project name','Mijn project':'My project','Projectmap':'Project folder','Document root':'Document root','Lokaal domein':'Local domain','.localhost werkt zonder beheerderstoestemming.':'.localhost works without administrator permission.','PHP-versie':'PHP version','Volledig offline':'Fully offline','HTTPS en hosts':'HTTPS and hosts','Online projecttemplate':'Online project template','Website aanmaken':'Create website','Annuleren':'Cancel','Gebruik na toevoegen de knop Domeinen & HTTPS herstellen.':'After adding, use Repair domains & HTTPS.',
 'Start':'Start','Stop':'Stop','Opslaan':'Save','Verwijderen':'Delete','Verwijder':'Delete','Herstellen':'Restore','Vernieuwen':'Refresh','Controleren':'Check','Uitvoeren':'Run','Toevoegen':'Add','Aanmaken':'Create','Openen':'Open','Importeren':'Import','Exporteren':'Export','Kiezen':'Choose','Sluiten':'Close','Later':'Later','Meten':'Measure','Opnieuw':'Retry','Terugdraaien':'Roll back','Inspecteren':'Inspect','Installeren…':'Installing…','Starten…':'Starting…','Poorten controleren':'Check ports','Poorten controleren…':'Checking ports…','Alles starten':'Start all','Alles stoppen':'Stop all','Alles controleren':'Check all','Alles controleren & herstellen':'Check & repair all','Nu controleren':'Check now','Nu installeren':'Install now','Veilig herstellen':'Safe repair','Automatisch oplossen':'Resolve automatically','Domeinen & HTTPS herstellen':'Repair domains & HTTPS',
 'Gereed':'Ready','GEREED':'READY','Geslaagd':'Passed','Mislukt':'Failed','Fout':'Error','Aandacht':'Attention','Actie nodig':'Action required','Gepland':'Queued','Bezig':'Running','Geannuleerd':'Cancelled','Gestopt':'Stopped','GESTOPT':'STOPPED','ACTIEF':'RUNNING','Ontbreekt':'Missing','ONTBREEKT':'MISSING','Niet gereed':'Not ready','Goed':'Good','GEZOND':'HEALTHY','Actueel':'Current','Gewijzigd':'Changed','Uitgeschakeld':'Disabled','Zelfstandig':'Independent','In gebruik door LocalDeck':'Used by LocalDeck','Extern bezet':'Occupied externally','Gereserveerd':'Reserved','Poort is vrij':'Port is available','Poort hoort bij LocalDeck':'Port belongs to LocalDeck','Poort is beschikbaar':'Port is available','Alle poorten zijn gecontroleerd':'All ports have been checked',
 'Service':'Service','Poort':'Port','Nieuwe luisterpoort':'New listening port','Status/eigenaar':'Status/owner','Binding':'Binding','Protocol':'Protocol','Direct servicebeheer':'Direct service management','Start, stop of wijzig iedere service afzonderlijk':'Start, stop or change each service individually','Andere programma\'s worden nooit gestopt. Is de gekozen poort bezet, dan blijft de huidige configuratie intact.':'Other programs are never stopped. If the selected port is occupied, the current configuration remains unchanged.','LocalDeck controleert alle zes poorten en herkent de eigenaar.':'LocalDeck checks all six ports and identifies the owner.','Veilige poortwissel':'Safe port change','De nieuwe poort wordt gecontroleerd en opgeslagen.':'The new port is checked and saved.','De service wordt kort gestopt, aangepast en automatisch opnieuw gestart.':'The service is briefly stopped, changed and restarted automatically.','LocalDeck controleert de service en de luisterpoort.':'LocalDeck checks the service and listening port.','Poort succesvol gewijzigd':'Port changed successfully','Poort gecontroleerd':'Port checked','Poortconflicten gevonden':'Port conflicts found','Poortconflict blijft bestaan':'Port conflict remains',
 'Start precies wat een werkdag nodig heeft':'Start exactly what your workday needs','Een profiel start vereisten automatisch en stopt services die niet bij het profiel horen.':'A profile starts requirements automatically and stops services outside the profile.','Startprofielen':'Start profiles','Profiel opslaan':'Save profile','Naam eigen profiel':'Custom profile name','Startprofiel verwijderen':'Delete start profile','Afhankelijkheidsgrafiek':'Dependency graph','PHP lifecycle':'PHP lifecycle','Port Autopilot 2.0':'Port Autopilot 2.0','Primaire en secundaire bindingen, TCP/UDP, IPv4/IPv6, reserveringen en proceseigenaren.':'Primary and secondary bindings, TCP/UDP, IPv4/IPv6, reservations and process owners.','Port Autopilot 2 controleren':'Run Port Autopilot 2','Queues & schedulers':'Queues & schedulers','Langlopende projectprocessen starten verborgen en bewaren hun laatste uitvoer.':'Long-running project processes start hidden and retain their latest output.','Worker toevoegen':'Add worker','Worker verwijderen':'Delete worker','Workernaam':'Worker name','Uitvoerbaar bestand':'Executable','Argumenten':'Arguments','Profielen respecteren service-afhankelijkheden. Workers draaien verborgen, zonder DOS-venster, en stoppen mee met LocalDeck.':'Profiles respect service dependencies. Workers run hidden without a console window and stop with LocalDeck.',
 'Elke belangrijke actie blijft controleerbaar':'Every important action remains auditable','Voortgang, deelstappen, fouten en herstelpunten blijven bewaard, ook na een herstart van LocalDeck.':'Progress, steps, errors and restore points are retained, even after restarting LocalDeck.','Afgeronde acties wissen':'Clear completed actions','Nog geen acties':'No actions yet','Rehearsals, releasecontroles, poortwijzigingen en workers verschijnen hier automatisch.':'Rehearsals, release checks, port changes and workers appear here automatically.','Actie uit lijst verwijderen':'Remove action from list','Actie niet uitgevoerd':'Action not completed',
 'Van lokale wijziging naar aantoonbaar releasegereed':'From local change to demonstrably release-ready','Alle controles blijven offline en lokaal; elke uitvoering verschijnt met stappen in het Action Center.':'All checks remain offline and local; every run appears with steps in the Action Center.','Actief kwaliteitsproject':'Active quality project','Rehearsal Mode':'Rehearsal Mode','Kopieert het project tijdelijk, controleert locks, syntax, migraties en tests zonder de bron te wijzigen.':'Temporarily copies the project and checks locks, syntax, migrations and tests without modifying the source.','Release Gate':'Release Gate','Combineert preflight, dependencies, drift, SBOM, performance en browserresultaten tot één besluit.':'Combines preflight, dependencies, drift, SBOM, performance and browser results into one decision.','Performancebaseline':'Performance baseline','Meet vijf lokale requests en markeert regressies ten opzichte van de vorige baseline.':'Measures five local requests and flags regressions against the previous baseline.','Browsermatrix':'Browser matrix','Rendert desktop, tablet en mobiel in Chromium en bewaart controleerbare screenshots.':'Renders desktop, tablet and mobile in Chromium and stores verifiable screenshots.','Dependency Guard':'Dependency Guard','Voert Composer validate/audit uit en controleert reproduceerbare PHP- en Node-lockfiles.':'Runs Composer validate/audit and checks reproducible PHP and Node lockfiles.','SBOM & licenties':'SBOM & licenses','Genereert lokaal een CycloneDX 1.5-inventaris uit Composer- en Node-lockfiles.':'Generates a local CycloneDX 1.5 inventory from Composer and Node lockfiles.','DB Migration Lab':'DB Migration Lab','Leest migratiestatus en risico’s zonder een schemawijziging uit te voeren.':'Reads migration status and risks without changing the schema.','Team Drift Detector':'Team Drift Detector','Vergelijkt werkmap, Project Capsule, lockfile en toegewezen PHP-runtime.':'Compares workspace, Project Capsule, lockfile and assigned PHP runtime.','Mail Quality Lab':'Mail Quality Lab','Beoordeelt onderwerp, afzender, ontvangers, inhoud en bijlagen van de nieuwste lokale mail.':'Reviews subject, sender, recipients, content and attachments of the latest local email.','Dev Drive-assistent':'Dev Drive assistant','Controleer Dev Drive en inspecteer een .ldpack zonder het archief uit te pakken.':'Check Dev Drive and inspect an .ldpack without extracting the archive.','Recente kwaliteitsrapporten':'Recent quality reports','Start een kwaliteitscontrole om het eerste rapport te maken.':'Run a quality check to create the first report.','Publicatie blijft geblokkeerd zolang kritieke controles falen.':'Publishing remains blocked while critical checks fail.',
 'Lokale integraties testen zonder externe dienst':'Test local integrations without an external service','Importeer OpenAPI, voer alleen lokale requests uit, vang webhooks op en speel veilige requestopnames opnieuw af.':'Import OpenAPI, run local requests only, capture webhooks and replay safe request recordings.','OpenAPI importeren':'Import OpenAPI','API Studio':'API Studio','OpenAPI 3 JSON/YAML of een handmatige lokale basis-URL.':'OpenAPI 3 JSON/YAML or a manual local base URL.','Werkruimtenaam':'Workspace name','Werkruimte':'Workspace','Werkruimte toevoegen':'Add workspace','Kies werkruimte':'Choose workspace','Kies endpoint':'Choose endpoint','Endpoint':'Endpoint','Testdata':'Test data','Request':'Request','API-werkruimte verwijderen':'Delete API workspace','Importeer OpenAPI of maak een handmatige werkruimte.':'Import OpenAPI or create a manual workspace.','Webhook Catcher':'Webhook Catcher','Endpoint luistert alleen op 127.0.0.1 en heeft geen account of activatie nodig.':'The endpoint listens only on 127.0.0.1 and requires no account or activation.','Webhooknaam':'Webhook name','Nieuwe webhook':'New webhook','Webhook-URL kopiëren':'Copy webhook URL','Webhook verwijderen':'Delete webhook','Lokale replaybestemming':'Local replay destination','Nog geen webhooks ontvangen.':'No webhooks received yet.','LocalDeck Replay':'LocalDeck Replay','Bewaar een lokale requestopname zonder autorisatieheaders of cookies en speel hem later opnieuw af.':'Store a local request recording without authorization headers or cookies and replay it later.','Opname bewaren':'Save recording','Replay-opname verwijderen':'Delete replay recording','Nog niet afgespeeld':'Not replayed yet','Lege respons':'Empty response','(lege body)':'(empty body)',
 'Projectprofielen & isolatie':'Project profiles & isolation','Eigen poorten, runtimekeuzes, debugpagina en overdraagbare .localdeck.yml Project Capsule.':'Dedicated ports, runtime choices, debug page and portable .localdeck.yml Project Capsule.','GEÏSOLEERD':'ISOLATED','GEDEELD':'SHARED','niet geïnstalleerd':'not installed','Geïsoleerde poorten':'Isolated ports','Developerpagina':'Developer page','Capsule opslaan':'Save capsule','Voeg eerst een project toe om een geïsoleerd profiel te maken.':'Add a project first to create an isolated profile.','Database-inspector':'Database inspector','Bekijk tabellen en voer veilige, alleen-lezen SQL uit. Wijzigingen blijven in phpMyAdmin.':'View tables and run safe, read-only SQL. Changes remain in phpMyAdmin.','Selecteer een database':'Select a database','Tabellen laden':'Load tables','Tabellen':'Tables','Kies een database en laad de tabellen.':'Choose a database and load its tables.','SQL-editor':'SQL editor','alleen lezen':'read only','SQL-opdracht':'SQL command','rijen':'rows','automatisch beperkt tot 200':'automatically limited to 200',
 'Herstelpunten voor bestanden, database, configuratie en lokale mail':'Restore points for files, database, configuration and local mail','Maak vóór risicovolle wijzigingen één herstelpunt. `node_modules`, Git-data en logbestanden worden niet dubbel opgeslagen.':'Create one restore point before risky changes. `node_modules`, Git data and logs are not duplicated.','Kies project':'Choose project','Omschrijving':'Description','Voor upgrade naar…':'Before upgrading to…','Herstelpunt maken':'Create restore point','herstelpunten':'restore points','Lokale Time Machine-archieven in de gegevensmap van LocalDeck.':'Local Time Machine archives in the LocalDeck data folder.','Geen omschrijving':'No description','Herstelpunt verwijderen':'Delete restore point','Er zijn nog geen herstelpunten gemaakt.':'No restore points have been created yet.',
 'Terugkerend werk met één klik':'Recurring work with one click','Composer, npm, PHPUnit en frameworkopdrachten draaien verborgen in de projectmap; uitvoer verschijnt in het LocalDeck-logboek.':'Composer, npm, PHPUnit and framework commands run hidden in the project folder; output appears in the LocalDeck activity log.','Actief project':'Active project','Nog niet uitgevoerd':'Not run yet','Eigen taak toevoegen':'Add custom task','Alleen een uitvoerbaar bestand plus losse argumenten; shellconstructies worden bewust niet uitgevoerd.':'Only an executable and separate arguments; shell constructs are intentionally not executed.','Naam':'Name','Uitvoerbaar bestand, bijv. php':'Executable, e.g. php','Argumenten, bijv. artisan queue:work --once':'Arguments, e.g. artisan queue:work --once','Taak verwijderen':'Delete task',
 'Scan je lokale ontwikkelomgeving':'Scan your local development environment','Controleert runtimebestanden, updates, HTTPS, gevoelige projectbestanden en reproduceerbare dependencies.':'Checks runtime files, updates, HTTPS, sensitive project files and reproducible dependencies.','Scan starten':'Start scan','Bevindingen':'Findings','Alles blijft lokaal; er worden geen projectbestanden verstuurd.':'Everything remains local; no project files are sent.','Start de scan om bevindingen te bekijken.':'Run the scan to view findings.','Herstel succesvol afgerond':'Repair completed successfully','Herstel afgerond met aandachtspunten':'Repair completed with warnings',
 'Een ecosysteem zonder het basispakket op te blazen':'An ecosystem without bloating the base package','Schakel templates en adapters in, importeer bestaande omgevingen en deel projectconfiguratie via .localdeck.json.':'Enable templates and adapters, import existing environments and share project configuration through .localdeck.json.','.localdeck.json importeren':'Import .localdeck.json','beschikbaar':'available','adapter / voorbereiding':'adapter / preparation','Migreer vanaf een bestaande stack':'Migrate from an existing stack','Projectmappen blijven staan; LocalDeck voegt alleen profielen en domeinen toe.':'Project folders remain in place; LocalDeck only adds profiles and domains.','XAMPP importeren':'Import XAMPP','WampServer importeren':'Import WampServer','Laragon importeren':'Import Laragon',
 'Ingebouwde offline runtime':'Built-in offline runtime','Alle 13 Windows-onderdelen worden met exacte patchversies en SHA-256 geleverd.':'All 13 Windows components are included with exact patch versions and SHA-256.','pakketten':'packages','Volledig offline gereed':'Fully offline ready','Installatiepakket is onvolledig':'Installation package is incomplete','Ingebouwde pakketten ontbreken':'Built-in packages are missing','SHA-256 controleren':'Verify SHA-256','Pakketkopie exporteren':'Export package copy','geverifieerd':'verified','controle nodig':'verification required','ontbreekt':'missing','Apache, PHP 8.2–8.5, MySQL, phpMyAdmin, Mailpit, Redis, Composer, WinSW, mkcert en de VC++ runtime staan al in het programma. De runtime-installatie maakt geen internetverbinding.':'Apache, PHP 8.2–8.5, MySQL, phpMyAdmin, Mailpit, Redis, Composer, WinSW, mkcert and the VC++ runtime are included in the application. Runtime installation does not connect to the internet.',
 'Uitgaande mailroute':'Outgoing mail route','Gebruik Mailpit, een eigen lokale mailserver of een externe SMTP-relay.':'Use Mailpit, your own local mail server or an external SMTP relay.','Modus':'Mode','Mailpit opvangen':'Capture with Mailpit','Lokale SMTP/IMAP-server':'Local SMTP/IMAP server','Externe SMTP-relay':'External SMTP relay','SMTP-host':'SMTP host','Gebruikersnaam':'Username','Configuratie testen':'Test configuration','Netwerk, prestaties & integraties':'Network, performance & integrations','Beheer .test-domeinen, lokale toegang, resourcegebruik en updatevertrouwen.':'Manage .test domains, local access, resource usage and trusted updates.','Lokale domeinen':'Local domains','Windows hosts-bestand':'Windows hosts file','LocalDeck DNS-service voor *.test':'LocalDeck DNS service for *.test','DNS-modus vraagt eenmalig beheerderstoestemming.':'DNS mode requires administrator permission once.','Eco-modus':'Eco mode','Stopt app-services automatisch wanneer projecten niet worden gebruikt.':'Automatically stops app services when projects are not in use.','Stop na inactiviteit':'Stop after inactivity','Nooit automatisch':'Never automatically','15 minuten':'15 minutes','30 minuten':'30 minutes','1 uur':'1 hour','2 uur':'2 hours','Alleen van toepassing in app-modus.':'Only applies in app mode.','Taal / Language':'Language / Taal','Nederlands':'Nederlands','Engels':'English','De taal wordt direct toegepast in LocalDeck, Webbeheer en Mailbeheer.':'The language is applied immediately in LocalDeck, Web Management and Mail Management.',
 'Installeer de ontwikkelstack':'Install the development stack','De Windows-runtime moet nog worden geïnstalleerd.':'The Windows runtime still needs to be installed.','Je ontwikkelomgeving staat klaar.':'Your development environment is ready.','Beheer de volledige Windows-stack, lokale websites, databases en testmail zonder consolevensters.':'Manage the complete Windows stack, local websites, databases and test email without console windows.','Runtime installeren':'Install runtime','Installeer de native Windows-runtime':'Install the native Windows runtime','Daarna werken localhost, phpMyAdmin, Mailpit, databases en de Windows-servicemodus echt.':'Afterwards localhost, phpMyAdmin, Mailpit, databases and Windows service mode work for real.','Installeer eerst de Windows-runtime':'Install the Windows runtime first','Installatie bezig…':'Installation in progress…','Runtime gereed':'Runtime ready','Runtime wordt geïnstalleerd…':'Runtime is being installed…','Runtime voorbereiden…':'Preparing runtime…','Windows-runtime gereed':'Windows runtime ready','Runtime nog niet geïnstalleerd':'Runtime not installed yet','Runtime ontbreekt of is onvolledig. Klik op Nu installeren.':'Runtime is missing or incomplete. Click Install now.',
 'Snelle instellingen':'Quick settings','Belangrijkste keuzes direct beschikbaar':'Key choices immediately available','Start LocalDeck met Windows':'Start LocalDeck with Windows','Minimaliseren naar systeemvak':'Minimize to tray','Automatische back-ups':'Automatic backups','Automatisch updates controleren':'Check for updates automatically','Updates en back-ups':'Updates and backups','Updatekanaal':'Update channel','Stabiel':'Stable','Bèta':'Beta','Back-upschema':'Backup schedule','Uit':'Off','Dagelijks':'Daily','Wekelijks':'Weekly','Bewaren per database':'Retain per database','Privacy en diagnose':'Privacy and diagnostics','Lokale gegevens blijven lokaal':'Local data stays local','Gegevensmap':'Data folder','Anonieme diagnostiek':'Anonymous diagnostics','Standaard uit; deze versie verstuurt niets.':'Off by default; this version sends nothing.','Veilig diagnoserapport exporteren':'Export safe diagnostics report',
 'LOCALDECK INSTELLINGEN':'LOCALDECK SETTINGS','Instellingen zonder eindeloos scrollen':'Settings without endless scrolling','Kies links een onderwerp. Alleen de instellingen die daarbij horen blijven in beeld.':'Choose a category on the left. Only its settings remain visible.','Instellingencategorieën':'Settings categories','Algemeen':'General','Taal en programmagedrag':'Language and app behavior','Netwerk & domeinen':'Network & domains','Lokale toegang en integraties':'Local access and integrations','Updates & back-ups':'Updates & backups','Versies, herstel en vertrouwen':'Versions, recovery and trust','Privacy & beveiliging':'Privacy & security','Lokale gegevens en diagnose':'Local data and diagnostics','Website, documentatie en downloads':'Website, documentation and downloads','Website & documentatie':'Website & documentation','Hulp nodig?':'Need help?','Handleidingen en downloads staan op LocalDeck.nl.':'Guides and downloads are available at LocalDeck.nl.','Website openen':'Open website','LocalDeck.nl openen':'Open LocalDeck.nl','Website geopend':'Website opened','LocalDeck.nl is geopend in je standaardbrowser.':'LocalDeck.nl has been opened in your default browser.',
 'Direct toepassen in alle LocalDeck-onderdelen':'Apply directly across all LocalDeck components','Ook voor Webbeheer, Mailbeheer en nieuwe startpagina\'s.':'Also applies to Web Management, Mail Management and new start pages.','Bepaal wanneer de lokale services actief blijven':'Choose when local services remain active','Services stoppen met LocalDeck.':'Services stop with LocalDeck.','Services blijven zelfstandig draaien.':'Services keep running independently.','Services herstellen na crash':'Restore services after a crash','Herstart alleen eerder gewenste app-services.':'Restarts only previously requested app services.','Stopt ongebruikte app-services automatisch.':'Stops unused app services automatically.','Het rode kruis verbergt LocalDeck bij de Windows-pictogrammen.':'The red close button hides LocalDeck in the Windows tray.','Het rode kruis sluit LocalDeck volledig af.':'The red close button exits LocalDeck completely.','Rode kruis: LocalDeck blijft actief':'Red close button: LocalDeck stays active','Rode kruis: LocalDeck wordt afgesloten':'Red close button: LocalDeck exits','Na een klik op × vind je LocalDeck terug bij de verborgen pictogrammen van Windows. Dubbelklik daar op het LocalDeck-pictogram om het venster weer te openen.':'After clicking ×, LocalDeck remains in the hidden Windows tray icons. Double-click the LocalDeck icon there to reopen the window.','Schakel Minimaliseren naar systeemvak in als services en LocalDeck na een klik op × actief moeten blijven.':'Enable Minimize to tray if LocalDeck and its services should remain active after clicking ×.',
 'Veilige standaard voor nieuwe projecten':'Safe default for new projects','Standaard domein':'Default domain','Bestaande projecten worden niet hernoemd.':'Existing projects are not renamed.','Lokale DNS vraagt eenmalig beheerderstoestemming.':'Local DNS requires administrator permission once.','Lokale toegang':'Local access','Beheer interfaces en lokale integraties':'Manage interfaces and local integrations','Tijdelijk delen via LAN':'Temporarily share over LAN','Maakt alleen lokaal een tijdelijke tokenlink.':'Creates a temporary token link on your local network only.','Lokale MCP-integratie':'Local MCP integration','Geeft editors uitsluitend ingebouwde LocalDeck-tools.':'Gives editors access only to built-in LocalDeck tools.','Officiële LocalDeck-website':'Official LocalDeck website','Nieuws, documentatie, community en alle beschikbare versies.':'News, documentation, community and all available versions.','Naar LocalDeck.nl':'Go to LocalDeck.nl',
 'Updates':'Updates','Releasekanaal en automatische controle':'Release channel and automatic checks','Toont een melding zodra een nieuwe versie bestaat.':'Shows a notification as soon as a new version is available.','Stabiel of vroege bètaversies.':'Stable or early beta versions.','Machineleesbare Windows-updatefeed.':'Machine-readable Windows update feed.','Feed vernieuwen':'Refresh feed','Back-ups':'Backups','Schema en bewaartermijn per database':'Schedule and retention per database','Maakt back-ups volgens het gekozen schema.':'Creates backups according to the selected schedule.','Moment waarop LocalDeck back-ups maakt.':'When LocalDeck creates backups.','Oudere exemplaren worden automatisch opgeruimd.':'Older copies are cleaned up automatically.','Updatevertrouwen':'Update trust','Hashes, Windows-handtekeningen en veilig terugdraaien':'Hashes, Windows signatures and safe rollback','Atomische updates':'Atomic updates','Bewaart de laatst gezonde versie.':'Keeps the last healthy version.','Controleert Authenticode na SHA-256.':'Checks Authenticode after SHA-256.','Exacte certificaatnaam.':'Exact certificate name.','Volledige SHA-1-thumbprint aanbevolen.':'Full SHA-1 thumbprint recommended.','Rollbackinstaller downloaden':'Download rollback installer',
 'Lokale gegevens':'Local data','Projecten en runtimegegevens blijven op deze computer':'Projects and runtime data remain on this computer','Zelf bepalen wat LocalDeck registreert':'Control what LocalDeck records','Gecombineerde servicelogs':'Combined service logs','Voegt Apache, PHP en MySQL lokaal samen.':'Combines Apache, PHP and MySQL locally.','Lokale controles en betrouwbare runtime':'Local checks and a trusted runtime','Voert uitsluitend lokale controles uit.':'Runs local checks only.','Gebundelde runtime verplicht':'Bundled runtime required','Installaties gebruiken alleen gecontroleerde offline pakketten.':'Installations use verified offline packages only.','Diagnoserapport':'Diagnostics report','Exporteer een veilig lokaal rapport zonder geheime waarden.':'Export a safe local report without secret values.',
 'NIEUWE VERSIE BESCHIKBAAR':'NEW VERSION AVAILABLE','LOCALDECK IS ACTUEEL':'LOCALDECK IS CURRENT','UPDATECONTROLE':'UPDATE CHECK','Je gebruikt de nieuwste versie.':'You are using the latest version.','Controleren is niet gelukt.':'The check failed.','Er staat een nieuwe versie van LocalDeck klaar met verbeteringen en updates.':'A new LocalDeck version is available with improvements and updates.','Veilig downloaden':'Download safely','WELKOM BIJ LOCALDECK':'WELCOME TO LOCALDECK','Hoe moeten je services draaien?':'How should your services run?','Kies een modus. LocalDeck installeert daarna automatisch Apache, PHP, MySQL, phpMyAdmin, Mailpit en Redis.':'Choose a mode. LocalDeck will then install Apache, PHP, MySQL, phpMyAdmin, Mailpit and Redis automatically.','Zoals XAMPP':'Like XAMPP','Services draaien alleen zolang LocalDeck actief is.':'Services run only while LocalDeck is active.','Windows-services':'Windows services','Services starten met Windows en blijven zelfstandig actief.':'Services start with Windows and keep running independently.','Altijd stil op de achtergrond':'Always quiet in the background','Geen CMD- of PowerShell-vensters; servicemodus vraagt eenmalig Windows-toestemming.':'No CMD or PowerShell windows; service mode requires Windows permission once.','Runtime installeren en doorgaan':'Install runtime and continue',
 'Nog niets toegevoegd':'Nothing added yet','Geen project':'No project','Voeg eerst een project toe.':'Add a project first.','Selecteer eerst een project.':'Select a project first.','Nog niet gecontroleerd.':'Not checked yet.','Geen update in behandeling.':'No update in progress.','Vorige sessie is netjes afgesloten.':'Previous session closed cleanly.','De vorige LocalDeck-sessie is niet netjes afgesloten.':'The previous LocalDeck session did not close cleanly.','Onderbroken doordat LocalDeck werd afgesloten.':'Interrupted because LocalDeck was closed.',
 'Project Blueprint':'Project Blueprint','Reproduceerbaar, overdraagbaar en exact vergrendeld':'Reproducible, portable and precisely locked','Projectgereedschap':'Project tools','WordPress, Laravel, Symfony, PHP, Composer, editor en terminal.':'WordPress, Laravel, Symfony, PHP, Composer, editor and terminal.','Projectcockpit':'Project cockpit','Projectgebruik en upgradeprioriteit in één overzicht.':'Project usage and upgrade priority in one overview.','Projectrecepten':'Project recipes','Branchomgevingen':'Branch environments','Kloon, detecteer, vergrendel en start':'Clone, detect, lock and start','Git repository URL':'Git repository URL','Git branchnaam':'Git branch name','Klonen en toevoegen':'Clone and add','Nog geen geïsoleerde branchomgevingen.':'No isolated branch environments yet.','Frameworkacties en Xdebug Workbench per PHP-versie':'Framework actions and Xdebug Workbench per PHP version','Request Timeline':'Request Timeline','OpenTelemetry-achtige lokale spans met trace- en servicecontext':'OpenTelemetry-style local spans with trace and service context','Klik op Meten om servicelogs en requests in te lezen.':'Click Measure to load service logs and requests.','Als LocalDeck Replay bewaren':'Save as LocalDeck Replay','Request als replay bewaren':'Save request as replay',
 'Databasegebruikers & rechten':'Database users & permissions','Maak een lokale gebruiker die uitsluitend rechten krijgt op één gekozen database.':'Create a local user with access to one selected database only.','Gebruiker maken':'Create user','Database voor gebruiker':'Database for user','MySQL-databases':'MySQL databases','Aanmaken, importeren, exporteren, herstellen en veilig verwijderen.':'Create, import, export, restore and safely delete.','Nieuwe database':'New database','Kies database':'Choose database','Back-ups vernieuwen':'Refresh backups','Nog geen databaseback-ups gemaakt.':'No database backups have been created yet.','Lokaal testadres':'Local test address','Nieuw testadres':'New test address','Bijvoorbeeld info@webshop.test of klant@example.test':'For example info@webshop.test or customer@example.test','Mailbeheer Pro':'Mail Management Pro','Mailpit vangt lokaal alle ontvangers op. LocalDeck Mailbeheer organiseert ze als virtuele inboxen en biedt zoeken, bronweergave en bulkbeheer.':'Mailpit captures all recipients locally. LocalDeck Mail Management organizes them as virtual inboxes with search, source view and bulk management.','Open LocalDeck Mailbeheer':'Open LocalDeck Mail Management',
 'PRODUCT DOCTOR':'PRODUCT DOCTOR','Één controlepunt voor projecten en releases':'One checkpoint for projects and releases','Controleer projectpaden, PHP, domeinen, vhosts, lockfiles, databases, HTTPS en de integriteit van alle gebundelde onderdelen.':'Check project paths, PHP, domains, vhosts, lockfiles, databases, HTTPS and the integrity of all bundled components.','Project voor Product Doctor':'Project for Product Doctor','Projectgezondheid':'Project health','Productiepariteit':'Production parity','Preflight':'Preflight','Testlab':'Test lab','Releasegereedheid':'Release readiness','Opnieuw beoordelen':'Reassess','Veilig herstel past alleen LocalDeck-configuratie aan.':'Safe repair only changes LocalDeck configuration.',
 'Beveiligingslijn':'Security baseline','Releasekanaal en gegevensbescherming':'Release channel and data protection','Alleen ondertekende updates':'Signed updates only','Beveiligingsscan bij starten':'Security scan on startup','Windows Secret Vault':'Windows Secret Vault','Waarden worden met Windows DPAPI versleuteld en nooit in de capsule geschreven.':'Values are encrypted with Windows DPAPI and never written to the capsule.','Geheime waarde':'Secret value','Globaal':'Global','Versleuteld opslaan':'Store encrypted','Nog geen geheime waarden opgeslagen.':'No secret values stored yet.','Vertrouwde update-uitgever':'Trusted update publisher','Vertrouwde componentuitgever':'Trusted component publisher',
 'LOCAL SECURITY':'LOCAL SECURITY','LOCAL MAIL':'LOCAL MAIL','DEVELOPER INSPECTOR':'DEVELOPER INSPECTOR','LOCALDECK CONTROL CENTER':'LOCALDECK CONTROL CENTER','AUTOMATION & SERVICES':'AUTOMATION & SERVICES','QUALITY & RELEASE LAB':'QUALITY & RELEASE LAB','API, WEBHOOKS & REPLAY':'API, WEBHOOKS & REPLAY','UITBREIDINGEN & MIGRATIE':'EXTENSIONS & MIGRATION','TIME MACHINE':'TIME MACHINE','TASK RUNNER':'TASK RUNNER',
 'Interfacetaal':'Interface language','De taal wordt direct toegepast in LocalDeck, Webbeheer, Mailbeheer en nieuwe lokale startpagina’s.':'The language is applied immediately in LocalDeck, Web Management, Mail Management and new local start pages.','Bij een nieuwe installatie kiest LocalDeck automatisch Nederlands op een Nederlandstalige Windows-installatie; op andere systemen wordt Engels gebruikt.':'For a new installation, LocalDeck automatically selects Dutch on a Dutch-language Windows installation; English is used on other systems.',
 'phpMyAdmin beheer':'phpMyAdmin management','LocalDeck Mailbeheer':'LocalDeck Mail Management','Stopt met LocalDeck':'Stops with LocalDeck','Draait met Windows':'Runs with Windows','HTTP-webserver':'HTTP web server','Relationele database':'Relational database','Databasebeheer in de browser':'Database management in the browser','Lokale e-mail inbox':'Local email inbox','Diagnose':'Diagnostics','Diagnostiek':'Diagnostics',
 'Services en gedrag':'Services and behavior','Kies exact hoe LocalDeck werkt':'Choose exactly how LocalDeck works','App-modus':'App mode','Services stoppen bij afsluiten':'Services stop on exit','services stoppen bij afsluiten':'services stop on exit','Blijven zelfstandig draaien':'Keep running independently','Open het dashboard na aanmelden.':'Open the dashboard after signing in.','Opent het dashboard na aanmelden.':'Opens the dashboard after signing in.','Sluiten verbergt het dashboard.':'Closing hides the dashboard.','Services automatisch herstellen':'Restart services automatically','Maximaal drie herstelpogingen in app-modus.':'Up to three recovery attempts in app mode.','Alleen lokaal op 127.0.0.1':'Local only on 127.0.0.1','Toont een melding wanneer een nieuwe versie bestaat.':'Shows a notification when a new version is available.','Updatefeed-URL':'Update feed URL','Volledige stack':'Full stack','Alle lokale services voor dagelijks ontwikkelwerk.':'All local services for daily development.','Webontwikkeling':'Web development','Apache, PHP, database en mail zonder Redis of phpMyAdmin.':'Apache, PHP, database and mail without Redis or phpMyAdmin.','PHP, MySQL, Redis en mail voor API- en workerwerk.':'PHP, MySQL, Redis and mail for API and worker tasks.','Minimaal':'Minimal','Alleen Apache en de vereiste PHP-runtime.':'Apache and the required PHP runtime only.','INGEBOUWD':'BUILT IN','Toepassen':'Apply',
 'Eigen SSL-certificaat actief':'Dedicated SSL certificate active','SSL-certificaat wordt voorbereid':'SSL certificate is being prepared','HTTPS actief':'HTTPS active','SSL voorbereiden':'Prepare SSL','Volledig verwijderen':'Delete completely','DEFINITIEF VERWIJDEREN':'PERMANENT DELETION','Niet alleen de koppeling, maar de volledige lokale projectomgeving wordt verwijderd.':'This removes the complete local project environment, not only its LocalDeck link.','Deze actie kan niet ongedaan worden gemaakt.':'This action cannot be undone.','Controleer de onderstaande onderdelen en maak zo nodig eerst een export of snapshot.':'Review the items below and create an export or snapshot first if needed.','Projectmap en alle bestanden':'Project folder and all files','Gekoppelde database en back-ups':'Linked database and backups','Geen gekoppelde database':'No linked database','SSL-certificaat, domein en Apache-vhost':'SSL certificate, domain and Apache virtual host','Alle gekoppelde LocalDeck-gegevens':'All linked LocalDeck data','Typ':'Type','om definitief te bevestigen':'to confirm permanent deletion','Alles definitief verwijderen':'Delete everything permanently','Services en koppelingen worden veilig gestopt voordat de gegevens worden gewist.':'Services and links are stopped safely before the data is deleted.','Project volledig verwijderd':'Project completely deleted'
};

Object.assign(english,{
 'Open, beheer, test en herstel je website vanuit één scherm.':'Open, manage, test and repair your website from one screen.',
 'Eén controle- en herstelplek voor LocalDeck en al je projecten.':'One check and repair center for LocalDeck and all your projects.',
 'Requests, PHP, SQL, taken, webhooks en logs in één inbox.':'Requests, PHP, SQL, tasks, webhooks and logs in one inbox.',
 'Interfacemodus':'Interface mode','Kies hoeveel gereedschap je dagelijks in beeld wilt':'Choose how many tools you want to see every day',
 'Eenvoudig':'Simple','Geavanceerd':'Advanced','Eenvoudige modus':'Simple mode','Geavanceerde modus':'Advanced mode',
 'Dagelijkse functies en duidelijke taal.':'Everyday features and plain language.','Alle ontwikkel-, kwaliteits- en automatiseringstools.':'All development, quality and automation tools.',
 'Eenvoudige modus actief':'Simple mode enabled','Geavanceerde modus actief':'Advanced mode enabled','Alle dagelijkse functies blijven direct bereikbaar.':'All everyday features remain directly accessible.','Alle ontwikkel- en kwaliteitstools zijn nu zichtbaar.':'All development and quality tools are now visible.',
 'GEAVANCEERD':'ADVANCED','PROJECTWERKPLEK':'PROJECT WORKSPACE','Actief project':'Active project','gezondheid':'health',
 'Werk aan project':'Work on project','automatische HTTPS':'automatic HTTPS','HTTPS wordt voorbereid':'HTTPS is being prepared','Database nog niet gekoppeld':'Database not linked yet',
 'Website & runtime':'Website & runtime','Open website':'Open website','Lokale e-mail':'Local email','Veilig werken':'Work safely','Ontwikkelen & debuggen':'Develop & debug','Controleren & herstellen':'Check & repair',
 'alle mail blijft lokaal':'all email stays local','Aanmaken en beheren':'Create and manage','Debug Inbox':'Debug Inbox','Requests, PHP, SQL en taken in één inbox':'Requests, PHP, SQL and tasks in one inbox',
 'Testkopie':'Test copy','Eigen map, poorten en gekloonde database.':'Dedicated folder, ports and cloned database.','Maak testkopie':'Create test copy','Nog geen testkopieën voor dit project.':'No test copies for this project yet.',
 'Tijdelijk delen':'Temporary sharing','Accountloze LAN-link met token en vervaldatum.':'Account-free LAN link with token and expiry.','Link maken':'Create link','Alleen bereikbaar binnen je lokale netwerk.':'Only accessible on your local network.','Schakel LAN-delen bewust in bij Instellingen.':'Enable LAN sharing deliberately in Settings.',
 'Begin met je eerste lokale website':'Start with your first local website','LocalDeck maakt de map, het domein, HTTPS en de ontwikkelomgeving automatisch voor je klaar.':'LocalDeck automatically prepares the folder, domain, HTTPS and development environment.','Nieuw project maken':'Create new project',
 'LOCALDECK FIX':'LOCALDECK FIX','punten kunnen beter':'items can be improved','Je lokale omgeving is gezond':'Your local environment is healthy','Een begrijpelijke controle van runtime, services, poorten, domeinen, HTTPS, projecten en beveiliging.':'A clear check of the runtime, services, ports, domains, HTTPS, projects and security.',
 'Alles veilig herstellen':'Repair everything safely','LocalDeck runtime':'LocalDeck runtime','Bestanden en configuratie in orde':'Files and configuration are healthy','Services & poorten':'Services & ports','Geen blokkades gevonden':'No blockers found','Projecten & HTTPS':'Projects & HTTPS','Alle projecten bereikbaar':'All projects are reachable','Geen open waarschuwingen':'No open warnings',
 'Projectgezondheid':'Project health','Alleen concrete problemen en veilige herstelacties.':'Only concrete problems and safe repair actions.','Klik op Alles controleren om projecten te beoordelen.':'Click Check all to assess projects.','LocalDeck en alle projecten zijn gezond.':'LocalDeck and all projects are healthy.',
 'DEBUG INBOX':'DEBUG INBOX','Alles wat aandacht vraagt, in één tijdlijn':'Everything needing attention in one timeline','Requests, PHP, SQL, queues, taken, webhooks en servicelogs zonder tussen schermen te wisselen.':'Requests, PHP, SQL, queues, tasks, webhooks and service logs without switching screens.',
 'gebeurtenissen':'events','aandacht':'attention','Alle projecten':'All projects','Alle typen':'All types','Alleen problemen':'Problems only','Servicelogs':'Service logs','Geen gebeurtenissen voor dit filter':'No events for this filter','Vernieuw de inbox of kies een ruimer filter.':'Refresh the inbox or choose a broader filter.',
 'Geavanceerd projectbeheer':'Advanced project management','Technische diagnose en overdracht':'Technical diagnostics and handover','Technische inspector en resources':'Technical inspector and resources',
 'SLIMME PROJECTWIZARD':'SMART PROJECT WIZARD','Wat wil je maken?':'What do you want to create?','LocalDeck vult de technische instellingen automatisch in.':'LocalDeck fills in the technical settings automatically.',
 'Nieuwe website':'New website','PHP of populair framework':'PHP or popular framework','Bestaande map':'Existing folder','Laat LocalDeck hem herkennen':'Let LocalDeck detect it','Vanuit Git':'From Git','Klonen en automatisch inrichten':'Clone and configure automatically',
 'Type website':'Website type','PHP-website (volledig offline)':'PHP website (fully offline)','Git-adres':'Git URL','Projectnaam (optioneel)':'Project name (optional)','Wordt uit het Git-adres gehaald':'Derived from the Git URL','Bestaande projectmap':'Existing project folder',
 'Geavanceerde instellingen':'Advanced settings','Automatisch startklaar':'Ready to start automatically','LocalDeck regelt de juiste PHP-versie, lokale URL, HTTPS, databaseprofiel, foutregistratie en IDE-integratie. Je hoeft niets te activeren of in te loggen.':'LocalDeck configures the right PHP version, local URL, HTTPS, database profile, error logging and IDE integration. No activation or sign-in is required.','Project maken en inrichten':'Create and configure project',
 'Project voorbereiden':'Preparing project','Services, domein en HTTPS worden gecontroleerd.':'Services, domain and HTTPS are being checked.','Werkplek voorbereiden':'Preparing workspace','Alles staat klaar':'Everything is ready','Project wordt ingericht':'Configuring project','Project is klaar':'Project is ready','De volledige lokale ontwikkelomgeving is aangemaakt en gecontroleerd.':'The complete local development environment has been created and checked.'
});

const patterns:Array<[RegExp,(match:RegExpMatchArray)=>string]>=[
 [/^(\d+) services actief$/,match=>`${match[1]} services running`],
 [/^(\d+) lokale projecten$/,match=>`${match[1]} local ${match[1]==='1'?'project':'projects'}`],
 [/^(\d+) projecten · (\d+) services actief$/,match=>`${match[1]} projects · ${match[2]} services running`],
 [/^(\d+) herstelpunten$/,match=>`${match[1]} restore points`],
 [/^(\d+) rijen$/,match=>`${match[1]} rows`],
 [/^Laatst: (.+) · code (.+)$/,match=>`Last: ${match[1]} · code ${match[2]}`],
 [/^(\d+) gebeurtenissen$/,match=>`${match[1]} events`],
 [/^(\d+) van (\d+) gebeurtenissen$/,match=>`${match[1]} of ${match[2]} events`],
 [/^Poort van (.+) wijzigen$/,match=>`Change ${match[1]} port`],
 [/^(\d+) controles uitgevoerd$/,match=>`${match[1]} checks completed`],
 [/^(\d+) kritieke punten vragen aandacht$/,match=>`${match[1]} critical items need attention`],
 [/^Versie (.+) is volledig bijgewerkt\.$/,match=>`Version ${match[1]} is fully up to date.`],
 [/^(\d+) pakketten$/,match=>`${match[1]} packages`],
 [/^Alleen lokaal op (.+)$/,match=>`Local only at ${match[1]}`],
 [/^(.+) volledig verwijderen\?$/,match=>`Delete ${match[1]} completely?`],
 [/^(.+) volledig verwijderen…$/,match=>`Deleting ${match[1]} completely…`],
 [/^(.+), de projectmap, database, SSL en alle gekoppelde LocalDeck-gegevens zijn verwijderd\.$/,match=>`${match[1]}, the project folder, database, SSL and all linked LocalDeck data have been deleted.`],
 [/^Typ exact "(.+)" om volledige verwijdering te bevestigen\.$/,match=>`Type "${match[1]}" exactly to confirm complete deletion.`],
 [/^(\d+) branchomgevingen · (\d+) snapshots · (\d+) mailadressen · (\d+) workers$/,match=>`${match[1]} branch environments · ${match[2]} snapshots · ${match[3]} mail addresses · ${match[4]} workers`],
 [/^(\d+) tekens · (\d+) replays$/,match=>`${match[1]} characters · ${match[2]} replays`]
];

const wordPatterns:Array<[RegExp,string]>=[
 [/\bmapmodus\b/gi,'folder mode'],
 [/\bpoorten\b/gi,'ports'],[/\bpoort\b/gi,'port'],[/\bprojecten\b/gi,'projects'],[/\bproject\b/gi,'project'],[/\bservices\b/gi,'services'],[/\bservice\b/gi,'service'],[/\bdatabases\b/gi,'databases'],[/\bdatabase\b/gi,'database'],[/\bherstelpunten\b/gi,'restore points'],[/\bback-ups\b/gi,'backups'],[/\bbestanden\b/gi,'files'],[/\bgebeurtenissen\b/gi,'events'],[/\bcontroles\b/gi,'checks'],[/\bcomponenten\b/gi,'components'],[/\bgeïnstalleerd\b/gi,'installed'],[/\bniet geïnstalleerd\b/gi,'not installed'],[/\bgestopt\b/gi,'stopped'],[/\bactief\b/gi,'running'],[/\bgereed\b/gi,'ready'],[/\bgeslaagd\b/gi,'passed'],[/\bmislukt\b/gi,'failed'],[/\boptioneel\b/gi,'optional'],[/\bstandaard\b/gi,'default'],[/\bglobaal\b/gi,'global'],[/\blokaal\b/gi,'local'],[/\bautomatisch\b/gi,'automatically'],[/\bopgeslagen\b/gi,'saved'],[/\bgecontroleerd\b/gi,'checked'],[/\bgevonden\b/gi,'found'],[/\bminuten\b/gi,'minutes'],[/\btekens\b/gi,'characters']
];

export function translateText(value:string,language:UiLanguage=activeLanguage){
 if(language==='nl'||!value)return value;
 const leading=value.match(/^\s*/)?.[0]??'',trailing=value.match(/\s*$/)?.[0]??'',source=value.trim();
 if(!source)return value;
 let translated=english[source];
 if(!translated)for(const[pattern,format]of patterns){const match=source.match(pattern);if(match){translated=format(match);break}}
 if(!translated){translated=source;for(const[pattern,replacement]of wordPatterns)translated=translated.replace(pattern,replacement)}
 return `${leading}${translated}${trailing}`;
}

export const localeFor=(language:UiLanguage=activeLanguage)=>language==='nl'?'nl-NL':'en-US';
export const languageName=(language:UiLanguage)=>language==='nl'?'Nederlands':'English';

interface TextMemory{source:string;rendered:string}
const textMemory=new WeakMap<CharacterData,TextMemory>(),attributeMemory=new WeakMap<Element,Map<string,TextMemory>>();
const skipped=(node:Node)=>node.parentElement?.closest('script,style,code,pre,textarea,[translate="no"],[data-no-translate]')!==null;

function renderTextNode(node:CharacterData,language:UiLanguage){
 if(skipped(node))return;
 const current=node.data,known=textMemory.get(node),source=known&&current===known.rendered?known.source:current,rendered=translateText(source,language);
 textMemory.set(node,{source,rendered});if(current!==rendered)node.data=rendered;
}

function renderAttributes(element:Element,language:UiLanguage){
 if(element.closest('[translate="no"],[data-no-translate]'))return;
 let remembered=attributeMemory.get(element);if(!remembered){remembered=new Map();attributeMemory.set(element,remembered)}
 for(const name of['title','aria-label','placeholder']){const current=element.getAttribute(name);if(current===null)continue;const known=remembered.get(name),source=known&&current===known.rendered?known.source:current,rendered=translateText(source,language);remembered.set(name,{source,rendered});if(current!==rendered)element.setAttribute(name,rendered)}
}

function renderTree(root:Node,language:UiLanguage){
 if(root.nodeType===Node.TEXT_NODE){renderTextNode(root as CharacterData,language);return}
 if(root.nodeType!==Node.ELEMENT_NODE&&root.nodeType!==Node.DOCUMENT_NODE&&root.nodeType!==Node.DOCUMENT_FRAGMENT_NODE)return;
 if(root instanceof Element)renderAttributes(root,language);
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT);let current=walker.nextNode();while(current){if(current.nodeType===Node.TEXT_NODE)renderTextNode(current as CharacterData,language);else renderAttributes(current as Element,language);current=walker.nextNode()}
}

let dialogsPatched=false,nativeConfirm:typeof window.confirm,nativePrompt:typeof window.prompt,nativeAlert:typeof window.alert;
function patchDialogs(){if(dialogsPatched)return;dialogsPatched=true;nativeConfirm=window.confirm.bind(window);nativePrompt=window.prompt.bind(window);nativeAlert=window.alert.bind(window);window.confirm=(message?:string)=>nativeConfirm(translateText(String(message??'')));window.prompt=(message?:string,defaultValue?:string)=>nativePrompt(translateText(String(message??'')),defaultValue);window.alert=(message?:unknown)=>nativeAlert(translateText(String(message??'')))}

export function installDocumentTranslations(language:UiLanguage){
 activeLanguage=language;document.documentElement.lang=language;document.title=language==='nl'?'LocalDeck — Windows-ontwikkeling':'LocalDeck — Windows development';patchDialogs();renderTree(document.body,language);
 const observer=new MutationObserver(records=>{for(const record of records){if(record.type==='characterData')renderTextNode(record.target as CharacterData,language);else{for(const node of record.addedNodes)renderTree(node,language);if(record.type==='attributes')renderAttributes(record.target as Element,language)}}});
 observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['title','aria-label','placeholder']});
 return()=>observer.disconnect();
}
