import{useState}from'react';
import{ArchiveRestore,Beaker,CheckCircle2,Cpu,Database,Download,FileArchive,KeyRound,Laptop,PackageCheck,Play,RefreshCw,Route,ShieldCheck,Stethoscope,Trash2,Upload,Wrench,XCircle}from'lucide-react';
import type{StateAction}from'./ControlCenter';

const StatusIcon=({status}:{status:'ok'|'warning'|'error'})=>status==='ok'?<CheckCircle2/>:status==='error'?<XCircle/>:<ShieldCheck/>;

export function OperationsCenter({state,action}:{state:AppState;action:StateAction}){
 const[activeProject,setActiveProject]=useState(state.projects[0]?.id||'');
 const[secretKey,setSecretKey]=useState(''),[secretValue,setSecretValue]=useState(''),[secretProject,setSecretProject]=useState(''),[serviceId,setServiceId]=useState<ServiceId>('apache'),[databaseId,setDatabaseId]=useState(state.databases[0]?.id||'');
 const health=state.projectHealth.find(report=>report.projectId===activeProject),parity=state.productionParity.find(report=>report.projectId===activeProject),preflight=state.preflightReports.find(report=>report.projectId===activeProject),testlab=state.testLabReports.find(report=>report.projectId===activeProject),port=state.portConflicts.find(item=>item.serviceId===serviceId),project=state.projects.find(item=>item.id===activeProject);
 const saveSecret=async()=>{if(!secretKey||!secretValue)return;if(await action(()=>window.localdeck.saveSecret(secretKey,secretValue,secretProject||undefined))){setSecretKey('');setSecretValue('')}};
 return <>
  <section className="featureHero operationsHero"><div><span className="eyebrow"><Stethoscope/>PRODUCT DOCTOR</span><h2>Één controlepunt voor projecten en releases</h2><p>Controleer projectpaden, PHP, domeinen, vhosts, lockfiles, databases, HTTPS en de integriteit van alle gebundelde onderdelen.</p></div><button className="primary big" onClick={()=>action(()=>window.localdeck.runProjectDoctor())}><RefreshCw/>Alles controleren</button></section>
  <div className="operationsGrid">
   <section className="panel doctorPanel"><div className="panelHead"><div><h3>Projectgezondheid</h3><p>Veilig herstel past alleen LocalDeck-configuratie aan.</p></div><Stethoscope/></div><select aria-label="Project voor Product Doctor" value={activeProject} onChange={event=>setActiveProject(event.target.value)}><option value="">Kies een project</option>{state.projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select>{health?<><div className={`scoreRing ${health.status}`}><strong>{health.score}</strong><small>/ 100</small></div><div className="doctorChecks">{health.checks.map(check=><div className={check.status} key={check.id}><StatusIcon status={check.status}/><span><b>{check.label}</b><small>{check.detail}</small></span></div>)}</div><button className="ghost" onClick={()=>action(()=>window.localdeck.repairProject(health.projectId))}><Wrench/>Veilig herstellen</button></>:<p className="emptyInline">Kies een project en start de controle.</p>}</section>
   <section className="panel readinessPanel"><div className="panelHead"><div><h3>Releasegereedheid</h3><p>Publicatie blijft geblokkeerd zolang kritieke controles falen.</p></div><ShieldCheck/></div><div className={`readinessScore ${state.releaseReadiness.status}`}><strong>{state.releaseReadiness.score}%</strong><span>{state.releaseReadiness.status==='ok'?'Gereed':state.releaseReadiness.status==='error'?'Niet gereed':'Actie nodig'}</span></div><div className="doctorChecks">{state.releaseReadiness.checks.map(check=><div className={check.status} key={check.id}><StatusIcon status={check.status}/><span><b>{check.label}</b><small>{check.detail}</small></span></div>)}</div><div className="toolbar"><button className="ghost" onClick={()=>action(()=>window.localdeck.assessReleaseReadiness())}><RefreshCw/>Opnieuw beoordelen</button><button className="primary" onClick={()=>action(()=>window.localdeck.verifyRuntimePackages())}><PackageCheck/>SHA-256 controleren</button></div></section>
  </div>
  <section className="panel full projectCockpit"><div className="panelHead"><div><h3>Projectcockpit</h3><p>Capsule, productiecontrole, lokale CI, browsertest en editorconfiguratie in één veilige stroom.</p></div><Beaker/></div><div className="cockpitTop"><select aria-label="Actief cockpitproject" value={activeProject} onChange={event=>setActiveProject(event.target.value)}><option value="">Kies een project</option>{state.projects.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><button className="ghost" disabled={!project} onClick={()=>action(()=>window.localdeck.writeProjectManifest(activeProject))}><PackageCheck/>Capsule schrijven</button><button className="ghost" disabled={!project} onClick={()=>action(()=>window.localdeck.runProductionParity(activeProject))}><Route/>Productie vergelijken</button><button className="primary" disabled={!project} onClick={()=>action(()=>window.localdeck.runPreflight(activeProject))}><Play/>Preflight</button><button className="primary" disabled={!project} onClick={()=>action(()=>window.localdeck.runTestLab(activeProject))}><Beaker/>Testlab</button><button className="ghost" disabled={!project} onClick={()=>action(()=>window.localdeck.writeIdeIntegration(activeProject))}><Laptop/>IDE instellen</button></div><div className="cockpitReports"><article className={parity?.status||'muted'}><span>Productiepariteit</span><strong>{parity?`${parity.score}/100`:'Nog niet getest'}</strong><small>{parity?.checks.find(item=>item.status!=='ok')?.detail||'Vergelijkt PHP, database, webserver, env-sleutels en lockfiles.'}</small></article><article className={preflight?.status||'muted'}><span>Lokale CI</span><strong>{preflight?`${preflight.steps.filter(item=>item.status==='ok').length}/${preflight.steps.length} geslaagd`:'Nog niet uitgevoerd'}</strong><small>{preflight?.steps.find(item=>item.status!=='ok')?.detail||'PHP lint, Composer, tests en productiepariteit.'}</small></article><article className={testlab?.status||'muted'}><span>Browser Testlab</span><strong>{testlab?`${testlab.durationMs} ms`:'Nog niet uitgevoerd'}</strong><small>{testlab?.checks.find(item=>item.status!=='ok')?.detail||'Controleert HTTP, inhoud, PHP-fouten en lokale assets.'}</small></article></div></section>
  <div className="operationsGrid securityTools">
   <section className="panel"><div className="panelHead"><div><h3>Windows Secret Vault</h3><p>Waarden worden met Windows DPAPI versleuteld en nooit in de capsule geschreven.</p></div><KeyRound/></div><div className="vaultForm"><input value={secretKey} onChange={event=>setSecretKey(event.target.value.toUpperCase())} placeholder="API_TOKEN"/><input type="password" value={secretValue} onChange={event=>setSecretValue(event.target.value)} placeholder="Geheime waarde"/><select value={secretProject} onChange={event=>setSecretProject(event.target.value)}><option value="">Globaal</option>{state.projects.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><button className="primary" disabled={secretKey.length<2||!secretValue} onClick={saveSecret}><KeyRound/>Versleuteld opslaan</button></div><div className="vaultList">{state.secretVault.map(secret=><div key={secret.id}><span><b>{secret.key}</b><small>{secret.scope==='global'?'Globaal':state.projects.find(item=>item.id===secret.projectId)?.name||'Project'} · {secret.encryption}</small></span><button className="iconButton danger" aria-label={`${secret.key} verwijderen`} onClick={()=>action(()=>window.localdeck.deleteSecret(secret.id))}><Trash2/></button></div>)}{!state.secretVault.length?<p className="emptyInline">Nog geen geheime waarden opgeslagen.</p>:null}</div></section>
   <section className="panel"><div className="panelHead"><div><h3>Port Autopilot</h3><p>Herken de eigenaar van een bezette poort en pas alleen LocalDeck veilig aan.</p></div><Cpu/></div><div className="portPilot"><select value={serviceId} onChange={event=>setServiceId(event.target.value as ServiceId)}>{state.services.map(service=><option value={service.id} key={service.id}>{service.name} · {service.port}</option>)}</select><button className="ghost" onClick={()=>action(async()=>{await window.localdeck.inspectPort(serviceId);return window.localdeck.getState()})}><RefreshCw/>Inspecteren</button><button className="primary" onClick={()=>action(()=>window.localdeck.portAutopilot(serviceId))}><Wrench/>Automatisch oplossen</button></div>{port?<div className={`portResult ${port.status}`}><strong>{port.status==='free'?'Poort is vrij':port.status==='localdeck'?'In gebruik door LocalDeck':'Extern bezet'}</strong><small>{port.ownerName?`${port.ownerName}${port.ownerPid?` · PID ${port.ownerPid}`:''}`:`Poort ${port.port}`} · voorstel {port.suggestedPort}</small>{port.ownerPath?<code>{port.ownerPath}</code>:null}</div>:<p className="emptyInline">Inspecteer een service om de poorteigenaar te zien.</p>}</section>
  </div>
  <div className="operationsGrid resilienceGrid">
   <section className="panel"><div className="panelHead"><div><h3>Veilige productie-import</h3><p>Back-up → SQL-import → automatische anonimisering van persoonsgegevens en tokens.</p></div><Database/></div><div className="safeImport"><select value={databaseId} onChange={event=>setDatabaseId(event.target.value)}><option value="">Kies database</option>{state.databases.map(database=><option value={database.id} key={database.id}>{database.name}</option>)}</select><button className="primary" disabled={!databaseId} onClick={()=>action(()=>window.localdeck.importDatabaseSanitized(databaseId))}><ShieldCheck/>Dump veilig importeren</button></div></section>
   <section className="panel"><div className="panelHead"><div><h3>Windows herstel & prestaties</h3><p>Crashherstel, atomische updates en Dev Drive blijven expliciet controleerbaar.</p></div><ArchiveRestore/></div><div className="resilienceStates"><div><b>Crashherstel</b><span className={state.crashRecovery.status}>{state.crashRecovery.status}</span><small>{state.crashRecovery.detail}</small></div><div><b>Atomische updates</b><span className={state.atomicUpdate.status}>{state.atomicUpdate.status}</span><small>{state.atomicUpdate.detail}</small></div><div><b>Dev Drive · {state.devDrive.drive}</b><span className={state.devDrive.status}>{state.devDrive.status}</span><small>{state.devDrive.detail}</small></div></div><button className="ghost" onClick={()=>action(()=>window.localdeck.detectDevDrive())}><RefreshCw/>Dev Drive controleren</button></section>
  </div>
  <section className="panel full workspacePanel"><div className="panelHead"><div><h3>Volledige werkruimte meenemen</h3><p>Websites, SQL-back-ups, snapshots, mail en geschoonde instellingen in één controleerbaar ZIP-archief. Wachtwoorden en privésleutels worden nooit opgenomen.</p></div><FileArchive/></div><div className="workspaceActions"><button className="primary" onClick={()=>action(()=>window.localdeck.exportWorkspace())}><Download/>Werkruimte exporteren</button><button className="ghost" onClick={()=>action(()=>window.localdeck.importWorkspace())}><Upload/>Naar lege map herstellen</button><button className="ghost" onClick={()=>action(()=>window.localdeck.exportSupportBundle())}><ArchiveRestore/>Veilige supportbundel</button></div></section>
  <section className="panel full"><div className="panelHead"><div><h3>Ondertekende offline componentpakketten</h3><p>Importeer alleen `.ldpack`-bestanden waarvan certificaat, manifest en iedere SHA-256-hash kloppen.</p></div><button className="primary" onClick={()=>action(()=>window.localdeck.importComponentPack())}><Upload/>.ldpack importeren</button></div><div className="packGrid">{state.componentPacks.map(pack=><article key={pack.id}><span>{pack.category}</span><b>{pack.name}{pack.version?` ${pack.version}`:''}</b><p>{pack.description}</p><small>{pack.status==='planned'?'Gepland':pack.status} · {pack.license}{pack.verified?' · ondertekend':''}</small></article>)}</div></section>
  <section className="panel full recipePanel"><div className="panelHead"><div><h3>Projectrecepten</h3><p>De projectwizard bevat direct bruikbare offline PHP-, WordPress-, Laravel-, Symfony- en Drupal-profielen.</p></div><Wrench/></div><div className="recipeGrid"><span>PHP website</span><span>WordPress</span><span>Laravel</span><span>Symfony</span><span>Drupal</span><span>Bestaande map</span></div></section>
 </>
}

export function DatabaseUsersPanel({state,action}:{state:AppState;action:StateAction}){
 const[users,setUsers]=useState<DatabaseUser[]>([]),[databaseId,setDatabaseId]=useState(state.databases[0]?.id||''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{try{setMessage('');setUsers(await window.localdeck.getDatabaseUsers())}catch(error){setMessage(error instanceof Error?error.message:String(error))}};
 const create=async()=>{if(!databaseId||!username||!password)return;if(await action(()=>window.localdeck.createDatabaseUser(databaseId,username,password))){setUsername('');setPassword('');await load()}};
 return <section className="panel full advancedSection"><div className="panelHead"><div><h3>Databasegebruikers & rechten</h3><p>Maak een lokale gebruiker die uitsluitend rechten krijgt op één gekozen database.</p></div><Database/></div><div className="databaseUserForm"><select aria-label="Database voor gebruiker" value={databaseId} onChange={event=>setDatabaseId(event.target.value)}><option value="">Kies database</option>{state.databases.map(database=><option key={database.id} value={database.id}>{database.name}</option>)}</select><input value={username} onChange={event=>setUsername(event.target.value)} placeholder="gebruikersnaam"/><input type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="minimaal 12 tekens"/><button className="primary" disabled={!databaseId||!username||password.length<12} onClick={create}>Gebruiker maken</button><button className="ghost" onClick={load}><RefreshCw/>Laden</button></div>{message&&<p className="inlineError">{message}</p>}<div className="databaseUsers">{users.map(user=><div key={`${user.user}@${user.host}`}><span><b>{user.user}@{user.host}</b><small>{user.plugin}{user.locked?' · vergrendeld':''}</small></span>{user.user!=='root'&&<button className="iconButton danger" aria-label={`${user.user} verwijderen`} onClick={async()=>{if(await action(()=>window.localdeck.deleteDatabaseUser(user.user,user.host)))await load()}}><Trash2/></button>}</div>)}</div></section>
}

export function MailRetentionPanel({state,action}:{state:AppState;action:StateAction}){
 const[maxMessages,setMaxMessages]=useState(state.settings.mailMaxMessages),[maxAge,setMaxAge]=useState(state.settings.mailMaxAgeDays);
 return <section className="panel full advancedSection"><div className="panelHead"><div><h3>Mailbeheer Pro</h3><p>Tags, bronweergave, .eml-export en HTML-, link- en spamcontroles staan in Webbeheer. Stel hier de lokale bewaartermijn in.</p></div><ArchiveRestore/></div><div className="mailRetention"><label>Maximaal aantal berichten<input type="number" min="50" max="100000" value={maxMessages} onChange={event=>setMaxMessages(Number(event.target.value))}/></label><label>Bewaren in dagen<input type="number" min="0" max="3650" value={maxAge} onChange={event=>setMaxAge(Number(event.target.value))}/><small>0 betekent geen tijdslimiet.</small></label><button className="primary" onClick={()=>action(()=>window.localdeck.updateSettings({mailMaxMessages:maxMessages,mailMaxAgeDays:maxAge}))}>Retentie opslaan</button></div></section>
}

export function DomainDefaultsPanel({state,action}:{state:AppState;action:StateAction}){
 return <section className="panel full advancedSection domainDefaults"><div className="panelHead"><div><h3>Lokale domeinen zonder UAC</h3><p>.localhost werkt standaard via Windows en de browser. .test blijft beschikbaar voor compatibiliteit.</p></div><ShieldCheck/></div><div className="extraSettings"><label><span>Standaard voor nieuwe projecten</span><select value={state.settings.localDomainSuffix} onChange={event=>action(()=>window.localdeck.updateSettings({localDomainSuffix:event.target.value as AppSettings['localDomainSuffix']}))}><option value="localhost">.localhost — zonder hosts-wijziging</option><option value="test">.test — hosts of lokale DNS nodig</option></select><small>Bestaande projectdomeinen worden niet onverwacht hernoemd.</small></label></div></section>
}
