import{useEffect,useState}from'react';
import{Activity,Boxes,Braces,CheckCircle2,Clipboard,CloudCog,CodeXml,Database,Download,FolderGit2,Gauge,GitBranch,GitFork,HardDrive,KeyRound,Network,PackageCheck,Play,RefreshCw,RotateCcw,Route,ShieldCheck,Sparkles,Square,Terminal,Timer,Trash2,Upload,Users}from'lucide-react';
import type{StateAction}from'./ControlCenter';

function selectedProject(state:AppState,id:string){return state.projects.find(project=>project.id===id)??state.projects[0]}

export function StudioPage({state,action}:{state:AppState;action:StateAction}){
 const[repository,setRepository]=useState(''),[parent,setParent]=useState(''),[cloneName,setCloneName]=useState(''),[projectId,setProjectId]=useState(state.projects[0]?.id??''),[branch,setBranch]=useState('feature/nieuwe-functie');
 const project=selectedProject(state,projectId),blueprint=state.blueprints.find(item=>item.projectId===project?.id),branches=state.branchEnvironments.filter(item=>item.projectId===project?.id);
 const chooseParent=async()=>{const directory=await window.localdeck.chooseDirectory();if(directory)setParent(directory)};
 const clone=async()=>{if(!repository||!parent)return;const ok=await action(()=>window.localdeck.cloneProject(repository,parent,cloneName||undefined));if(ok){setRepository('');setCloneName('')}};
 return <>
  <section className="studioHero"><div><span className="eyebrow"><FolderGit2/>GIT NAAR HTTPS IN ÉÉN STROOM</span><h2>Kloon, detecteer, vergrendel en start</h2><p>LocalDeck herkent WordPress, Laravel, Symfony en Drupal, maakt een geïsoleerd profiel en legt de runtime vast zonder automatisch destructieve migraties uit te voeren.</p></div><div className="cloneForm"><input aria-label="Git repository URL" value={repository} onChange={event=>setRepository(event.target.value)} placeholder="https://github.com/team/project.git"/><div><input aria-label="Optionele projectnaam" value={cloneName} onChange={event=>setCloneName(event.target.value)} placeholder="Optionele naam"/><button className="ghost" onClick={chooseParent}><HardDrive/>Doelmap</button></div><small>{parent||'Kies een bovenliggende projectmap'}</small><button className="primary" disabled={!repository||!parent} onClick={clone}><Download/>Klonen en toevoegen</button></div></section>
  <div className="studioColumns">
   <section className="panel"><div className="panelHead"><div><h3>Project Blueprint</h3><p>Reproduceerbaar, overdraagbaar en exact vergrendeld</p></div><button className="iconButton" aria-label="Blueprints verversen" onClick={()=>action(()=>window.localdeck.refreshBlueprints())}><RefreshCw/></button></div>
    <label className="studioSelect"><span>Project</span><select value={project?.id??''} onChange={event=>setProjectId(event.target.value)}>{state.projects.filter(item=>!item.parentProjectId).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    {project&&blueprint?<div className="blueprintCard"><div className="blueprintStatus"><div className={blueprint.locked?'locked':'drift'}>{blueprint.locked?<CheckCircle2/>:<Route/>}<span>{blueprint.locked?'CAPSULE KOMT OVEREEN':'CONFIGURATIEDRIFT'}</span></div><code>{blueprint.hash.slice(0,16)}</code></div><h3>{project.name}</h3><p>{blueprint.summary}</p><dl><div><dt>Domein</dt><dd>{project.domain}</dd></div><div><dt>Project Capsule</dt><dd>.localdeck.yml · schema {blueprint.schemaVersion}</dd></div><div><dt>PHP-pool</dt><dd>127.0.0.1:{9000+(project.phpVersion===state.settings.defaultPhpVersion?0:10+Math.max(0,['8.2','8.3','8.4','8.5'].indexOf(project.phpVersion)))}</dd></div></dl>{blueprint.warnings.map(warning=><small className="blueprintWarning" key={warning}>{warning}</small>)}<div className="miniActions"><button onClick={()=>action(()=>window.localdeck.bootstrapProject(project.id))}><Sparkles/>Automatisch inrichten</button><button onClick={()=>action(()=>window.localdeck.writeProjectManifest(project.id))}><PackageCheck/>Capsule vergrendelen</button><button onClick={()=>action(()=>window.localdeck.writeIdeIntegration(project.id))}><Terminal/>IDE-integratie</button><button onClick={()=>window.localdeck.openProject(project.id,'folder')}><CodeXml/>Map openen</button></div></div>:<p className="emptyInline">Voeg eerst een project toe.</p>}
   </section>
    <section className="panel"><div className="panelHead"><div><h3>Branchomgevingen</h3><p>Echte Git-worktree, eigen poorten en een gekloonde database per branch</p></div><GitFork/></div>{project?<><div className="branchCreate"><input aria-label="Git branchnaam" value={branch} onChange={event=>setBranch(event.target.value)} placeholder="feature/login"/><button className="primary" onClick={()=>action(()=>window.localdeck.createBranchEnvironment(project.id,branch))}><GitBranch/>Omgeving maken</button></div><div className="branchList">{branches.map(environment=><article key={environment.id}><GitBranch/><div><b>{environment.branch}</b><small>{environment.domain} · {environment.databaseCloned?'database gekloond':'eigen databaseprofiel'}</small></div><span>:{environment.httpPort}</span><button className="iconButton" aria-label={`${environment.branch} openen`} onClick={()=>window.localdeck.openProject(environment.childProjectId,'site')}><Play/></button><button className="iconButton danger" aria-label={`${environment.branch} verwijderen`} onClick={()=>action(()=>window.localdeck.removeBranchEnvironment(environment.id))}><Trash2/></button></article>)}{!branches.length?<p className="emptyInline">Nog geen geïsoleerde branchomgevingen.</p>:null}</div></>:<p className="emptyInline">Selecteer eerst een project.</p>}</section>
  </div>
  <ComponentMatrix state={state} action={action}/>
 </>
}

function ComponentMatrix({state,action}:{state:AppState;action:StateAction}){
 return <section className="panel componentPanel"><div className="panelHead"><div><h3>Runtimecomponenten</h3><p>Side-by-side versies, integriteitsstatus en gebruik per project</p></div><button className="ghost" onClick={()=>action(()=>window.localdeck.refreshComponents())}><RefreshCw/>Opnieuw scannen</button></div><div className="componentMatrix">{state.components.map(component=><article className={component.installed?'installed':'missing'} key={component.id}><div className="componentIcon">{component.category==='database'?<Database/>:component.category==='language'?<Braces/>:component.category==='tool'?<Terminal/>:<Boxes/>}</div><div><span>{component.category}</span><b>{component.name}</b><small>{component.description}</small></div><div className="componentState"><strong>{component.installed?'GEREED':'OPTIONEEL'}</strong><small>v{component.version}</small>{component.verified?<em><ShieldCheck/>geverifieerd</em>:null}</div></article>)}</div></section>
}

export function InspectorPage({state,action}:{state:AppState;action:StateAction}){
 const[projectId,setProjectId]=useState(state.projects[0]?.id??''),[actions,setActions]=useState<FrameworkAction[]>([]),[localError,setLocalError]=useState(''),[duration,setDuration]=useState(30),[leftDb,setLeftDb]=useState(state.databases[0]?.id??''),[rightDb,setRightDb]=useState(state.databases[1]?.id??''),[schema,setSchema]=useState<DatabaseSchemaDiff|null>(null),[testTable,setTestTable]=useState('users'),[testRows,setTestRows]=useState(10);
 const project=selectedProject(state,projectId),activeProjectId=project?.id,projectEvents=state.inspectorEvents.filter(event=>!project||!event.projectId||event.projectId===project.id).slice(0,80),activeShares=state.shares.filter(share=>share.status==='active');
 useEffect(()=>{if(!activeProjectId){setActions([]);return}let active=true;setLocalError('');window.localdeck.getFrameworkActions(activeProjectId).then(items=>{if(active)setActions(items)}).catch(reason=>{if(active)setLocalError(reason instanceof Error?reason.message:String(reason))});return()=>{active=false}},[activeProjectId]);
 const compare=async()=>{try{setLocalError('');setSchema(await window.localdeck.compareDatabaseSchemas(leftDb,rightDb))}catch(reason){setLocalError(reason instanceof Error?reason.message:String(reason))}};
 const captureEvent=(event:AppState['inspectorEvents'][number])=>{const source=state.projects.find(item=>item.id===event.projectId),match=event.title.match(/^(GET|POST|PUT|PATCH|DELETE|HEAD)\s+([^\s·]+)/);if(!source||!match)return;const port=source.profile?.isolated&&source.profile.httpPort?`:${source.profile.httpPort}`:'',url=`http://${source.domain}${port}${match[2]}`;void action(()=>window.localdeck.saveReplayCapture({projectId:source.id,name:`${match[1]} ${match[2]}`,method:match[1],url,headers:{'x-localdeck-replay':'1'},body:''}))};
 return <>
  <section className="inspectorHero"><div><span className="eyebrow"><Activity/>DEVELOPER INSPECTOR</span><h2>Van request tot database in één tijdlijn</h2><p>HTTP-verkeer, PHP-fouten, taken, beveiligingsmeldingen, Xdebug en resourcegebruik blijven volledig lokaal.</p></div><div className="resourceGauge"><Gauge/><strong>{state.resourceUsage.totalMemoryMb} MB</strong><span>LocalDeck + services</span><small>{state.resourceUsage.processes.length} actieve processen</small><button className="ghost" onClick={()=>action(()=>window.localdeck.refreshInspector())}><RefreshCw/>Meten</button></div></section>
  {localError?<div className="inlineError">{localError}</div>:null}
  <div className="studioColumns inspectorColumns">
   <section className="panel"><div className="panelHead"><div><h3>Projectgereedschap</h3><p>Frameworkacties en Xdebug Workbench per PHP-versie</p></div><Braces/></div><label className="studioSelect"><span>Project</span><select value={project?.id??''} onChange={event=>setProjectId(event.target.value)}>{state.projects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{project?<><label className="xdebugControl"><span><KeyRound/><b>Xdebug Workbench</b><small>Triggergestuurd op IDE-poort 9003; uitvoer blijft in de LocalDeck-map.</small></span><select value={project.profile?.xdebugMode||'off'} onChange={event=>action(()=>window.localdeck.setProjectXdebug(project.id,event.target.value as ProjectProfile['xdebugMode']))}><option value="off">Uit</option><option value="debug">Step debugging</option><option value="profile">Profiling</option><option value="trace">Functietrace</option><option value="coverage">Code coverage</option></select></label><div className="frameworkActions">{actions.map(item=><button disabled={!item.available} className={item.destructive?'dangerAction':''} key={item.id} onClick={()=>action(()=>window.localdeck.runFrameworkAction(project.id,item.id))}><Play/><span><b>{item.name}</b><small>{item.description}</small></span>{item.destructive?<em>BEVESTIGING</em>:null}</button>)}</div></>:<p className="emptyInline">Voeg eerst een project toe.</p>}</section>
   <section className="panel"><div className="panelHead"><div><h3>Tijdelijk delen</h3><p>Accountloze LAN-link met token, QR-code en automatische vervaldatum</p></div><Network/></div>{project?<><div className="shareCreate"><label><span>Geldigheid</span><select value={duration} onChange={event=>setDuration(Number(event.target.value))}><option value={15}>15 minuten</option><option value={30}>30 minuten</option><option value={60}>1 uur</option><option value={120}>2 uur</option></select></label><button className="primary" disabled={!state.settings.lanSharingEnabled} onClick={()=>action(()=>window.localdeck.startShare(project.id,duration))}><Upload/>LAN-link + QR maken</button></div>{!state.settings.lanSharingEnabled?<p className="panelHint">Schakel LAN-delen bewust in bij Instellingen. Internetdeling wordt niet automatisch geactiveerd.</p>:null}<div className="shareList">{activeShares.map(share=><article className="shareWithQr" key={share.id}>{share.qrDataUrl?<img src={share.qrDataUrl} alt={`QR-code voor ${share.url}`}/>:<Timer/>}<div><b>{state.projects.find(item=>item.id===share.projectId)?.name}</b><small>{share.url}</small></div><button className="iconButton" aria-label="Link kopiëren" onClick={()=>action(()=>window.localdeck.copyShare(share.id))}><Clipboard/></button><button className="iconButton" aria-label="Delen stoppen" onClick={()=>action(()=>window.localdeck.stopShare(share.id))}><Square/></button></article>)}</div></>:<p className="emptyInline">Selecteer eerst een project.</p>}<div className="integrationBox"><CloudCog/><div><b>CLI, IDE & lokale MCP</b><p>Preflight, status en veilige LocalDeck-tools zonder cloudaccount.</p></div><button className="ghost" disabled={!state.settings.mcpEnabled} onClick={()=>action(()=>window.localdeck.copyMcpConfig())}>MCP-config kopiëren</button><button className="ghost" onClick={()=>action(()=>window.localdeck.copyCliCommand())}>CLI-opdracht kopiëren</button></div></section>
  </div>
  <section className="panel databaseLab"><div className="panelHead"><div><h3>Database Lab</h3><p>Schemavergelijking, gecontroleerde testdata en privacyvriendelijke dumps</p></div><Database/></div><div className="databaseLabTools"><select aria-label="Linkerdatabase" value={leftDb} onChange={event=>setLeftDb(event.target.value)}>{state.databases.map(database=><option value={database.id} key={database.id}>{database.name}</option>)}</select><select aria-label="Rechterdatabase" value={rightDb} onChange={event=>setRightDb(event.target.value)}>{state.databases.map(database=><option value={database.id} key={database.id}>{database.name}</option>)}</select><button className="ghost" disabled={!leftDb||!rightDb||leftDb===rightDb} onClick={compare}><Route/>Schema vergelijken</button><input aria-label="Tabel voor testdata" value={testTable} onChange={event=>setTestTable(event.target.value)} placeholder="Tabelnaam"/><input aria-label="Aantal testdatariijen" type="number" min="1" max="100" value={testRows} onChange={event=>setTestRows(Number(event.target.value))}/><button className="ghost" disabled={!leftDb||!testTable} onClick={()=>action(()=>window.localdeck.generateTestData(leftDb,testTable,testRows))}><Users/>Testdata</button><button className="dangerButton" disabled={!leftDb} onClick={()=>action(()=>window.localdeck.anonymizeDatabase(leftDb))}><ShieldCheck/>Anonimiseren</button></div>{schema?<div className="schemaResult"><article><b>Alleen in {schema.left}</b>{schema.onlyLeft.map(name=><span key={name}>{name}</span>)}</article><article><b>Alleen in {schema.right}</b>{schema.onlyRight.map(name=><span key={name}>{name}</span>)}</article><article><b>Gewijzigd</b>{schema.changed.map(item=><span key={item.table}>{item.table}: {item.left} → {item.right}</span>)}</article></div>:null}</section>
  <section className="panel eventTimeline"><div className="panelHead"><div><h3>Request Timeline</h3><p>{projectEvents.length} OpenTelemetry-achtige lokale spans met trace- en servicecontext</p></div><Activity/></div>{projectEvents.map(event=><article className={event.severity} key={event.id}><i/><time>{new Date(event.at).toLocaleTimeString('nl-NL')}</time><span>{event.service||event.kind}</span><div><b>{event.title}</b><p>{event.detail}</p>{event.traceId&&<code>trace {event.traceId.slice(0,12)} · span {event.spanId}</code>}</div>{event.kind==='request'&&<button className="iconButton" title="Als LocalDeck Replay bewaren" aria-label="Request als replay bewaren" onClick={()=>captureEvent(event)}><RotateCcw/></button>}</article>)}{!projectEvents.length?<p className="emptyInline">Klik op Meten om servicelogs en requests in te lezen.</p>:null}</section>
 </>
}
